
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Kit: 'Kit',
  Store: 'Store',
  StoreLink: 'StoreLink',
  PriceEntry: 'PriceEntry',
  WishlistItem: 'WishlistItem',
  CollectionItem: 'CollectionItem',
  PriceAlert: 'PriceAlert'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const KitScalarFieldEnum = {
  id: 'id',
  name: 'name',
  grade: 'grade',
  series: 'series',
  scale: 'scale',
  releaseDate: 'releaseDate',
  imageUrl: 'imageUrl',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KitScalarFieldEnum = (typeof KitScalarFieldEnum)[keyof typeof KitScalarFieldEnum]


export const StoreScalarFieldEnum = {
  id: 'id',
  name: 'name',
  website: 'website',
  logoUrl: 'logoUrl',
  createdAt: 'createdAt'
} as const

export type StoreScalarFieldEnum = (typeof StoreScalarFieldEnum)[keyof typeof StoreScalarFieldEnum]


export const StoreLinkScalarFieldEnum = {
  id: 'id',
  kitId: 'kitId',
  storeId: 'storeId',
  url: 'url',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StoreLinkScalarFieldEnum = (typeof StoreLinkScalarFieldEnum)[keyof typeof StoreLinkScalarFieldEnum]


export const PriceEntryScalarFieldEnum = {
  id: 'id',
  kitId: 'kitId',
  storeId: 'storeId',
  price: 'price',
  currency: 'currency',
  inStock: 'inStock',
  recordedAt: 'recordedAt'
} as const

export type PriceEntryScalarFieldEnum = (typeof PriceEntryScalarFieldEnum)[keyof typeof PriceEntryScalarFieldEnum]


export const WishlistItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kitId: 'kitId',
  targetPrice: 'targetPrice',
  notes: 'notes',
  addedAt: 'addedAt'
} as const

export type WishlistItemScalarFieldEnum = (typeof WishlistItemScalarFieldEnum)[keyof typeof WishlistItemScalarFieldEnum]


export const CollectionItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kitId: 'kitId',
  purchasePrice: 'purchasePrice',
  purchaseDate: 'purchaseDate',
  notes: 'notes',
  addedAt: 'addedAt'
} as const

export type CollectionItemScalarFieldEnum = (typeof CollectionItemScalarFieldEnum)[keyof typeof CollectionItemScalarFieldEnum]


export const PriceAlertScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kitId: 'kitId',
  targetPrice: 'targetPrice',
  alertType: 'alertType',
  isActive: 'isActive',
  createdAt: 'createdAt',
  triggeredAt: 'triggeredAt'
} as const

export type PriceAlertScalarFieldEnum = (typeof PriceAlertScalarFieldEnum)[keyof typeof PriceAlertScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

