
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Kit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Kit
 * 
 */
export type KitModel = runtime.Types.Result.DefaultSelection<Prisma.$KitPayload>

export type AggregateKit = {
  _count: KitCountAggregateOutputType | null
  _min: KitMinAggregateOutputType | null
  _max: KitMaxAggregateOutputType | null
}

export type KitMinAggregateOutputType = {
  id: string | null
  name: string | null
  grade: string | null
  series: string | null
  scale: string | null
  releaseDate: Date | null
  imageUrl: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KitMaxAggregateOutputType = {
  id: string | null
  name: string | null
  grade: string | null
  series: string | null
  scale: string | null
  releaseDate: Date | null
  imageUrl: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KitCountAggregateOutputType = {
  id: number
  name: number
  grade: number
  series: number
  scale: number
  releaseDate: number
  imageUrl: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type KitMinAggregateInputType = {
  id?: true
  name?: true
  grade?: true
  series?: true
  scale?: true
  releaseDate?: true
  imageUrl?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type KitMaxAggregateInputType = {
  id?: true
  name?: true
  grade?: true
  series?: true
  scale?: true
  releaseDate?: true
  imageUrl?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type KitCountAggregateInputType = {
  id?: true
  name?: true
  grade?: true
  series?: true
  scale?: true
  releaseDate?: true
  imageUrl?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type KitAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Kit to aggregate.
   */
  where?: Prisma.KitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kits to fetch.
   */
  orderBy?: Prisma.KitOrderByWithRelationInput | Prisma.KitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Kits
  **/
  _count?: true | KitCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KitMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KitMaxAggregateInputType
}

export type GetKitAggregateType<T extends KitAggregateArgs> = {
      [P in keyof T & keyof AggregateKit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKit[P]>
    : Prisma.GetScalarType<T[P], AggregateKit[P]>
}




export type KitGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KitWhereInput
  orderBy?: Prisma.KitOrderByWithAggregationInput | Prisma.KitOrderByWithAggregationInput[]
  by: Prisma.KitScalarFieldEnum[] | Prisma.KitScalarFieldEnum
  having?: Prisma.KitScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KitCountAggregateInputType | true
  _min?: KitMinAggregateInputType
  _max?: KitMaxAggregateInputType
}

export type KitGroupByOutputType = {
  id: string
  name: string
  grade: string
  series: string | null
  scale: string | null
  releaseDate: Date | null
  imageUrl: string | null
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: KitCountAggregateOutputType | null
  _min: KitMinAggregateOutputType | null
  _max: KitMaxAggregateOutputType | null
}

type GetKitGroupByPayload<T extends KitGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KitGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KitGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KitGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KitGroupByOutputType[P]>
      }
    >
  >



export type KitWhereInput = {
  AND?: Prisma.KitWhereInput | Prisma.KitWhereInput[]
  OR?: Prisma.KitWhereInput[]
  NOT?: Prisma.KitWhereInput | Prisma.KitWhereInput[]
  id?: Prisma.StringFilter<"Kit"> | string
  name?: Prisma.StringFilter<"Kit"> | string
  grade?: Prisma.StringFilter<"Kit"> | string
  series?: Prisma.StringNullableFilter<"Kit"> | string | null
  scale?: Prisma.StringNullableFilter<"Kit"> | string | null
  releaseDate?: Prisma.DateTimeNullableFilter<"Kit"> | Date | string | null
  imageUrl?: Prisma.StringNullableFilter<"Kit"> | string | null
  description?: Prisma.StringNullableFilter<"Kit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Kit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Kit"> | Date | string
  priceEntries?: Prisma.PriceEntryListRelationFilter
  storeLinks?: Prisma.StoreLinkListRelationFilter
  wishlistItems?: Prisma.WishlistItemListRelationFilter
  collectionItems?: Prisma.CollectionItemListRelationFilter
  priceAlerts?: Prisma.PriceAlertListRelationFilter
}

export type KitOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  series?: Prisma.SortOrderInput | Prisma.SortOrder
  scale?: Prisma.SortOrderInput | Prisma.SortOrder
  releaseDate?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  priceEntries?: Prisma.PriceEntryOrderByRelationAggregateInput
  storeLinks?: Prisma.StoreLinkOrderByRelationAggregateInput
  wishlistItems?: Prisma.WishlistItemOrderByRelationAggregateInput
  collectionItems?: Prisma.CollectionItemOrderByRelationAggregateInput
  priceAlerts?: Prisma.PriceAlertOrderByRelationAggregateInput
}

export type KitWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KitWhereInput | Prisma.KitWhereInput[]
  OR?: Prisma.KitWhereInput[]
  NOT?: Prisma.KitWhereInput | Prisma.KitWhereInput[]
  name?: Prisma.StringFilter<"Kit"> | string
  grade?: Prisma.StringFilter<"Kit"> | string
  series?: Prisma.StringNullableFilter<"Kit"> | string | null
  scale?: Prisma.StringNullableFilter<"Kit"> | string | null
  releaseDate?: Prisma.DateTimeNullableFilter<"Kit"> | Date | string | null
  imageUrl?: Prisma.StringNullableFilter<"Kit"> | string | null
  description?: Prisma.StringNullableFilter<"Kit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Kit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Kit"> | Date | string
  priceEntries?: Prisma.PriceEntryListRelationFilter
  storeLinks?: Prisma.StoreLinkListRelationFilter
  wishlistItems?: Prisma.WishlistItemListRelationFilter
  collectionItems?: Prisma.CollectionItemListRelationFilter
  priceAlerts?: Prisma.PriceAlertListRelationFilter
}, "id">

export type KitOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  series?: Prisma.SortOrderInput | Prisma.SortOrder
  scale?: Prisma.SortOrderInput | Prisma.SortOrder
  releaseDate?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.KitCountOrderByAggregateInput
  _max?: Prisma.KitMaxOrderByAggregateInput
  _min?: Prisma.KitMinOrderByAggregateInput
}

export type KitScalarWhereWithAggregatesInput = {
  AND?: Prisma.KitScalarWhereWithAggregatesInput | Prisma.KitScalarWhereWithAggregatesInput[]
  OR?: Prisma.KitScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KitScalarWhereWithAggregatesInput | Prisma.KitScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Kit"> | string
  name?: Prisma.StringWithAggregatesFilter<"Kit"> | string
  grade?: Prisma.StringWithAggregatesFilter<"Kit"> | string
  series?: Prisma.StringNullableWithAggregatesFilter<"Kit"> | string | null
  scale?: Prisma.StringNullableWithAggregatesFilter<"Kit"> | string | null
  releaseDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Kit"> | Date | string | null
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"Kit"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Kit"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Kit"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Kit"> | Date | string
}

export type KitCreateInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertCreateNestedManyWithoutKitInput
}

export type KitUncheckedCreateInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryUncheckedCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkUncheckedCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemUncheckedCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemUncheckedCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertUncheckedCreateNestedManyWithoutKitInput
}

export type KitUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUpdateManyWithoutKitNestedInput
}

export type KitUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUncheckedUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUncheckedUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUncheckedUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUncheckedUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUncheckedUpdateManyWithoutKitNestedInput
}

export type KitCreateManyInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KitUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  series?: Prisma.SortOrder
  scale?: Prisma.SortOrder
  releaseDate?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KitMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  series?: Prisma.SortOrder
  scale?: Prisma.SortOrder
  releaseDate?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KitMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  series?: Prisma.SortOrder
  scale?: Prisma.SortOrder
  releaseDate?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KitScalarRelationFilter = {
  is?: Prisma.KitWhereInput
  isNot?: Prisma.KitWhereInput
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type KitCreateNestedOneWithoutStoreLinksInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutStoreLinksInput, Prisma.KitUncheckedCreateWithoutStoreLinksInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutStoreLinksInput
  connect?: Prisma.KitWhereUniqueInput
}

export type KitUpdateOneRequiredWithoutStoreLinksNestedInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutStoreLinksInput, Prisma.KitUncheckedCreateWithoutStoreLinksInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutStoreLinksInput
  upsert?: Prisma.KitUpsertWithoutStoreLinksInput
  connect?: Prisma.KitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KitUpdateToOneWithWhereWithoutStoreLinksInput, Prisma.KitUpdateWithoutStoreLinksInput>, Prisma.KitUncheckedUpdateWithoutStoreLinksInput>
}

export type KitCreateNestedOneWithoutPriceEntriesInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutPriceEntriesInput, Prisma.KitUncheckedCreateWithoutPriceEntriesInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutPriceEntriesInput
  connect?: Prisma.KitWhereUniqueInput
}

export type KitUpdateOneRequiredWithoutPriceEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutPriceEntriesInput, Prisma.KitUncheckedCreateWithoutPriceEntriesInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutPriceEntriesInput
  upsert?: Prisma.KitUpsertWithoutPriceEntriesInput
  connect?: Prisma.KitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KitUpdateToOneWithWhereWithoutPriceEntriesInput, Prisma.KitUpdateWithoutPriceEntriesInput>, Prisma.KitUncheckedUpdateWithoutPriceEntriesInput>
}

export type KitCreateNestedOneWithoutWishlistItemsInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutWishlistItemsInput, Prisma.KitUncheckedCreateWithoutWishlistItemsInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutWishlistItemsInput
  connect?: Prisma.KitWhereUniqueInput
}

export type KitUpdateOneRequiredWithoutWishlistItemsNestedInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutWishlistItemsInput, Prisma.KitUncheckedCreateWithoutWishlistItemsInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutWishlistItemsInput
  upsert?: Prisma.KitUpsertWithoutWishlistItemsInput
  connect?: Prisma.KitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KitUpdateToOneWithWhereWithoutWishlistItemsInput, Prisma.KitUpdateWithoutWishlistItemsInput>, Prisma.KitUncheckedUpdateWithoutWishlistItemsInput>
}

export type KitCreateNestedOneWithoutCollectionItemsInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutCollectionItemsInput, Prisma.KitUncheckedCreateWithoutCollectionItemsInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutCollectionItemsInput
  connect?: Prisma.KitWhereUniqueInput
}

export type KitUpdateOneRequiredWithoutCollectionItemsNestedInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutCollectionItemsInput, Prisma.KitUncheckedCreateWithoutCollectionItemsInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutCollectionItemsInput
  upsert?: Prisma.KitUpsertWithoutCollectionItemsInput
  connect?: Prisma.KitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KitUpdateToOneWithWhereWithoutCollectionItemsInput, Prisma.KitUpdateWithoutCollectionItemsInput>, Prisma.KitUncheckedUpdateWithoutCollectionItemsInput>
}

export type KitCreateNestedOneWithoutPriceAlertsInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutPriceAlertsInput, Prisma.KitUncheckedCreateWithoutPriceAlertsInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutPriceAlertsInput
  connect?: Prisma.KitWhereUniqueInput
}

export type KitUpdateOneRequiredWithoutPriceAlertsNestedInput = {
  create?: Prisma.XOR<Prisma.KitCreateWithoutPriceAlertsInput, Prisma.KitUncheckedCreateWithoutPriceAlertsInput>
  connectOrCreate?: Prisma.KitCreateOrConnectWithoutPriceAlertsInput
  upsert?: Prisma.KitUpsertWithoutPriceAlertsInput
  connect?: Prisma.KitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KitUpdateToOneWithWhereWithoutPriceAlertsInput, Prisma.KitUpdateWithoutPriceAlertsInput>, Prisma.KitUncheckedUpdateWithoutPriceAlertsInput>
}

export type KitCreateWithoutStoreLinksInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertCreateNestedManyWithoutKitInput
}

export type KitUncheckedCreateWithoutStoreLinksInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryUncheckedCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemUncheckedCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemUncheckedCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertUncheckedCreateNestedManyWithoutKitInput
}

export type KitCreateOrConnectWithoutStoreLinksInput = {
  where: Prisma.KitWhereUniqueInput
  create: Prisma.XOR<Prisma.KitCreateWithoutStoreLinksInput, Prisma.KitUncheckedCreateWithoutStoreLinksInput>
}

export type KitUpsertWithoutStoreLinksInput = {
  update: Prisma.XOR<Prisma.KitUpdateWithoutStoreLinksInput, Prisma.KitUncheckedUpdateWithoutStoreLinksInput>
  create: Prisma.XOR<Prisma.KitCreateWithoutStoreLinksInput, Prisma.KitUncheckedCreateWithoutStoreLinksInput>
  where?: Prisma.KitWhereInput
}

export type KitUpdateToOneWithWhereWithoutStoreLinksInput = {
  where?: Prisma.KitWhereInput
  data: Prisma.XOR<Prisma.KitUpdateWithoutStoreLinksInput, Prisma.KitUncheckedUpdateWithoutStoreLinksInput>
}

export type KitUpdateWithoutStoreLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUpdateManyWithoutKitNestedInput
}

export type KitUncheckedUpdateWithoutStoreLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUncheckedUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUncheckedUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUncheckedUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUncheckedUpdateManyWithoutKitNestedInput
}

export type KitCreateWithoutPriceEntriesInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  storeLinks?: Prisma.StoreLinkCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertCreateNestedManyWithoutKitInput
}

export type KitUncheckedCreateWithoutPriceEntriesInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  storeLinks?: Prisma.StoreLinkUncheckedCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemUncheckedCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemUncheckedCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertUncheckedCreateNestedManyWithoutKitInput
}

export type KitCreateOrConnectWithoutPriceEntriesInput = {
  where: Prisma.KitWhereUniqueInput
  create: Prisma.XOR<Prisma.KitCreateWithoutPriceEntriesInput, Prisma.KitUncheckedCreateWithoutPriceEntriesInput>
}

export type KitUpsertWithoutPriceEntriesInput = {
  update: Prisma.XOR<Prisma.KitUpdateWithoutPriceEntriesInput, Prisma.KitUncheckedUpdateWithoutPriceEntriesInput>
  create: Prisma.XOR<Prisma.KitCreateWithoutPriceEntriesInput, Prisma.KitUncheckedCreateWithoutPriceEntriesInput>
  where?: Prisma.KitWhereInput
}

export type KitUpdateToOneWithWhereWithoutPriceEntriesInput = {
  where?: Prisma.KitWhereInput
  data: Prisma.XOR<Prisma.KitUpdateWithoutPriceEntriesInput, Prisma.KitUncheckedUpdateWithoutPriceEntriesInput>
}

export type KitUpdateWithoutPriceEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  storeLinks?: Prisma.StoreLinkUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUpdateManyWithoutKitNestedInput
}

export type KitUncheckedUpdateWithoutPriceEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  storeLinks?: Prisma.StoreLinkUncheckedUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUncheckedUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUncheckedUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUncheckedUpdateManyWithoutKitNestedInput
}

export type KitCreateWithoutWishlistItemsInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertCreateNestedManyWithoutKitInput
}

export type KitUncheckedCreateWithoutWishlistItemsInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryUncheckedCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkUncheckedCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemUncheckedCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertUncheckedCreateNestedManyWithoutKitInput
}

export type KitCreateOrConnectWithoutWishlistItemsInput = {
  where: Prisma.KitWhereUniqueInput
  create: Prisma.XOR<Prisma.KitCreateWithoutWishlistItemsInput, Prisma.KitUncheckedCreateWithoutWishlistItemsInput>
}

export type KitUpsertWithoutWishlistItemsInput = {
  update: Prisma.XOR<Prisma.KitUpdateWithoutWishlistItemsInput, Prisma.KitUncheckedUpdateWithoutWishlistItemsInput>
  create: Prisma.XOR<Prisma.KitCreateWithoutWishlistItemsInput, Prisma.KitUncheckedCreateWithoutWishlistItemsInput>
  where?: Prisma.KitWhereInput
}

export type KitUpdateToOneWithWhereWithoutWishlistItemsInput = {
  where?: Prisma.KitWhereInput
  data: Prisma.XOR<Prisma.KitUpdateWithoutWishlistItemsInput, Prisma.KitUncheckedUpdateWithoutWishlistItemsInput>
}

export type KitUpdateWithoutWishlistItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUpdateManyWithoutKitNestedInput
}

export type KitUncheckedUpdateWithoutWishlistItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUncheckedUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUncheckedUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUncheckedUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUncheckedUpdateManyWithoutKitNestedInput
}

export type KitCreateWithoutCollectionItemsInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertCreateNestedManyWithoutKitInput
}

export type KitUncheckedCreateWithoutCollectionItemsInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryUncheckedCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkUncheckedCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemUncheckedCreateNestedManyWithoutKitInput
  priceAlerts?: Prisma.PriceAlertUncheckedCreateNestedManyWithoutKitInput
}

export type KitCreateOrConnectWithoutCollectionItemsInput = {
  where: Prisma.KitWhereUniqueInput
  create: Prisma.XOR<Prisma.KitCreateWithoutCollectionItemsInput, Prisma.KitUncheckedCreateWithoutCollectionItemsInput>
}

export type KitUpsertWithoutCollectionItemsInput = {
  update: Prisma.XOR<Prisma.KitUpdateWithoutCollectionItemsInput, Prisma.KitUncheckedUpdateWithoutCollectionItemsInput>
  create: Prisma.XOR<Prisma.KitCreateWithoutCollectionItemsInput, Prisma.KitUncheckedCreateWithoutCollectionItemsInput>
  where?: Prisma.KitWhereInput
}

export type KitUpdateToOneWithWhereWithoutCollectionItemsInput = {
  where?: Prisma.KitWhereInput
  data: Prisma.XOR<Prisma.KitUpdateWithoutCollectionItemsInput, Prisma.KitUncheckedUpdateWithoutCollectionItemsInput>
}

export type KitUpdateWithoutCollectionItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUpdateManyWithoutKitNestedInput
}

export type KitUncheckedUpdateWithoutCollectionItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUncheckedUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUncheckedUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUncheckedUpdateManyWithoutKitNestedInput
  priceAlerts?: Prisma.PriceAlertUncheckedUpdateManyWithoutKitNestedInput
}

export type KitCreateWithoutPriceAlertsInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemCreateNestedManyWithoutKitInput
}

export type KitUncheckedCreateWithoutPriceAlertsInput = {
  id?: string
  name: string
  grade: string
  series?: string | null
  scale?: string | null
  releaseDate?: Date | string | null
  imageUrl?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  priceEntries?: Prisma.PriceEntryUncheckedCreateNestedManyWithoutKitInput
  storeLinks?: Prisma.StoreLinkUncheckedCreateNestedManyWithoutKitInput
  wishlistItems?: Prisma.WishlistItemUncheckedCreateNestedManyWithoutKitInput
  collectionItems?: Prisma.CollectionItemUncheckedCreateNestedManyWithoutKitInput
}

export type KitCreateOrConnectWithoutPriceAlertsInput = {
  where: Prisma.KitWhereUniqueInput
  create: Prisma.XOR<Prisma.KitCreateWithoutPriceAlertsInput, Prisma.KitUncheckedCreateWithoutPriceAlertsInput>
}

export type KitUpsertWithoutPriceAlertsInput = {
  update: Prisma.XOR<Prisma.KitUpdateWithoutPriceAlertsInput, Prisma.KitUncheckedUpdateWithoutPriceAlertsInput>
  create: Prisma.XOR<Prisma.KitCreateWithoutPriceAlertsInput, Prisma.KitUncheckedCreateWithoutPriceAlertsInput>
  where?: Prisma.KitWhereInput
}

export type KitUpdateToOneWithWhereWithoutPriceAlertsInput = {
  where?: Prisma.KitWhereInput
  data: Prisma.XOR<Prisma.KitUpdateWithoutPriceAlertsInput, Prisma.KitUncheckedUpdateWithoutPriceAlertsInput>
}

export type KitUpdateWithoutPriceAlertsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUpdateManyWithoutKitNestedInput
}

export type KitUncheckedUpdateWithoutPriceAlertsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  series?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  releaseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceEntries?: Prisma.PriceEntryUncheckedUpdateManyWithoutKitNestedInput
  storeLinks?: Prisma.StoreLinkUncheckedUpdateManyWithoutKitNestedInput
  wishlistItems?: Prisma.WishlistItemUncheckedUpdateManyWithoutKitNestedInput
  collectionItems?: Prisma.CollectionItemUncheckedUpdateManyWithoutKitNestedInput
}


/**
 * Count Type KitCountOutputType
 */

export type KitCountOutputType = {
  priceEntries: number
  storeLinks: number
  wishlistItems: number
  collectionItems: number
  priceAlerts: number
}

export type KitCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  priceEntries?: boolean | KitCountOutputTypeCountPriceEntriesArgs
  storeLinks?: boolean | KitCountOutputTypeCountStoreLinksArgs
  wishlistItems?: boolean | KitCountOutputTypeCountWishlistItemsArgs
  collectionItems?: boolean | KitCountOutputTypeCountCollectionItemsArgs
  priceAlerts?: boolean | KitCountOutputTypeCountPriceAlertsArgs
}

/**
 * KitCountOutputType without action
 */
export type KitCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitCountOutputType
   */
  select?: Prisma.KitCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KitCountOutputType without action
 */
export type KitCountOutputTypeCountPriceEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PriceEntryWhereInput
}

/**
 * KitCountOutputType without action
 */
export type KitCountOutputTypeCountStoreLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoreLinkWhereInput
}

/**
 * KitCountOutputType without action
 */
export type KitCountOutputTypeCountWishlistItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WishlistItemWhereInput
}

/**
 * KitCountOutputType without action
 */
export type KitCountOutputTypeCountCollectionItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CollectionItemWhereInput
}

/**
 * KitCountOutputType without action
 */
export type KitCountOutputTypeCountPriceAlertsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PriceAlertWhereInput
}


export type KitSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  grade?: boolean
  series?: boolean
  scale?: boolean
  releaseDate?: boolean
  imageUrl?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  priceEntries?: boolean | Prisma.Kit$priceEntriesArgs<ExtArgs>
  storeLinks?: boolean | Prisma.Kit$storeLinksArgs<ExtArgs>
  wishlistItems?: boolean | Prisma.Kit$wishlistItemsArgs<ExtArgs>
  collectionItems?: boolean | Prisma.Kit$collectionItemsArgs<ExtArgs>
  priceAlerts?: boolean | Prisma.Kit$priceAlertsArgs<ExtArgs>
  _count?: boolean | Prisma.KitCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kit"]>

export type KitSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  grade?: boolean
  series?: boolean
  scale?: boolean
  releaseDate?: boolean
  imageUrl?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["kit"]>

export type KitSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  grade?: boolean
  series?: boolean
  scale?: boolean
  releaseDate?: boolean
  imageUrl?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["kit"]>

export type KitSelectScalar = {
  id?: boolean
  name?: boolean
  grade?: boolean
  series?: boolean
  scale?: boolean
  releaseDate?: boolean
  imageUrl?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type KitOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "grade" | "series" | "scale" | "releaseDate" | "imageUrl" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["kit"]>
export type KitInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  priceEntries?: boolean | Prisma.Kit$priceEntriesArgs<ExtArgs>
  storeLinks?: boolean | Prisma.Kit$storeLinksArgs<ExtArgs>
  wishlistItems?: boolean | Prisma.Kit$wishlistItemsArgs<ExtArgs>
  collectionItems?: boolean | Prisma.Kit$collectionItemsArgs<ExtArgs>
  priceAlerts?: boolean | Prisma.Kit$priceAlertsArgs<ExtArgs>
  _count?: boolean | Prisma.KitCountOutputTypeDefaultArgs<ExtArgs>
}
export type KitIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type KitIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $KitPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Kit"
  objects: {
    priceEntries: Prisma.$PriceEntryPayload<ExtArgs>[]
    storeLinks: Prisma.$StoreLinkPayload<ExtArgs>[]
    wishlistItems: Prisma.$WishlistItemPayload<ExtArgs>[]
    collectionItems: Prisma.$CollectionItemPayload<ExtArgs>[]
    priceAlerts: Prisma.$PriceAlertPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    grade: string
    series: string | null
    scale: string | null
    releaseDate: Date | null
    imageUrl: string | null
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["kit"]>
  composites: {}
}

export type KitGetPayload<S extends boolean | null | undefined | KitDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KitPayload, S>

export type KitCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KitFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KitCountAggregateInputType | true
  }

export interface KitDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Kit'], meta: { name: 'Kit' } }
  /**
   * Find zero or one Kit that matches the filter.
   * @param {KitFindUniqueArgs} args - Arguments to find a Kit
   * @example
   * // Get one Kit
   * const kit = await prisma.kit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KitFindUniqueArgs>(args: Prisma.SelectSubset<T, KitFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Kit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KitFindUniqueOrThrowArgs} args - Arguments to find a Kit
   * @example
   * // Get one Kit
   * const kit = await prisma.kit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KitFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KitFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitFindFirstArgs} args - Arguments to find a Kit
   * @example
   * // Get one Kit
   * const kit = await prisma.kit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KitFindFirstArgs>(args?: Prisma.SelectSubset<T, KitFindFirstArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitFindFirstOrThrowArgs} args - Arguments to find a Kit
   * @example
   * // Get one Kit
   * const kit = await prisma.kit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KitFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KitFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Kits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Kits
   * const kits = await prisma.kit.findMany()
   * 
   * // Get first 10 Kits
   * const kits = await prisma.kit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kitWithIdOnly = await prisma.kit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KitFindManyArgs>(args?: Prisma.SelectSubset<T, KitFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Kit.
   * @param {KitCreateArgs} args - Arguments to create a Kit.
   * @example
   * // Create one Kit
   * const Kit = await prisma.kit.create({
   *   data: {
   *     // ... data to create a Kit
   *   }
   * })
   * 
   */
  create<T extends KitCreateArgs>(args: Prisma.SelectSubset<T, KitCreateArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Kits.
   * @param {KitCreateManyArgs} args - Arguments to create many Kits.
   * @example
   * // Create many Kits
   * const kit = await prisma.kit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KitCreateManyArgs>(args?: Prisma.SelectSubset<T, KitCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Kits and returns the data saved in the database.
   * @param {KitCreateManyAndReturnArgs} args - Arguments to create many Kits.
   * @example
   * // Create many Kits
   * const kit = await prisma.kit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Kits and only return the `id`
   * const kitWithIdOnly = await prisma.kit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KitCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KitCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Kit.
   * @param {KitDeleteArgs} args - Arguments to delete one Kit.
   * @example
   * // Delete one Kit
   * const Kit = await prisma.kit.delete({
   *   where: {
   *     // ... filter to delete one Kit
   *   }
   * })
   * 
   */
  delete<T extends KitDeleteArgs>(args: Prisma.SelectSubset<T, KitDeleteArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Kit.
   * @param {KitUpdateArgs} args - Arguments to update one Kit.
   * @example
   * // Update one Kit
   * const kit = await prisma.kit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KitUpdateArgs>(args: Prisma.SelectSubset<T, KitUpdateArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Kits.
   * @param {KitDeleteManyArgs} args - Arguments to filter Kits to delete.
   * @example
   * // Delete a few Kits
   * const { count } = await prisma.kit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KitDeleteManyArgs>(args?: Prisma.SelectSubset<T, KitDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Kits
   * const kit = await prisma.kit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KitUpdateManyArgs>(args: Prisma.SelectSubset<T, KitUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kits and returns the data updated in the database.
   * @param {KitUpdateManyAndReturnArgs} args - Arguments to update many Kits.
   * @example
   * // Update many Kits
   * const kit = await prisma.kit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Kits and only return the `id`
   * const kitWithIdOnly = await prisma.kit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KitUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KitUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Kit.
   * @param {KitUpsertArgs} args - Arguments to update or create a Kit.
   * @example
   * // Update or create a Kit
   * const kit = await prisma.kit.upsert({
   *   create: {
   *     // ... data to create a Kit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Kit we want to update
   *   }
   * })
   */
  upsert<T extends KitUpsertArgs>(args: Prisma.SelectSubset<T, KitUpsertArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Kits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitCountArgs} args - Arguments to filter Kits to count.
   * @example
   * // Count the number of Kits
   * const count = await prisma.kit.count({
   *   where: {
   *     // ... the filter for the Kits we want to count
   *   }
   * })
  **/
  count<T extends KitCountArgs>(
    args?: Prisma.Subset<T, KitCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KitCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Kit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KitAggregateArgs>(args: Prisma.Subset<T, KitAggregateArgs>): Prisma.PrismaPromise<GetKitAggregateType<T>>

  /**
   * Group by Kit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KitGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KitGroupByArgs['orderBy'] }
      : { orderBy?: KitGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KitGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKitGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Kit model
 */
readonly fields: KitFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Kit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KitClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  priceEntries<T extends Prisma.Kit$priceEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Kit$priceEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  storeLinks<T extends Prisma.Kit$storeLinksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Kit$storeLinksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  wishlistItems<T extends Prisma.Kit$wishlistItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Kit$wishlistItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WishlistItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  collectionItems<T extends Prisma.Kit$collectionItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Kit$collectionItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CollectionItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  priceAlerts<T extends Prisma.Kit$priceAlertsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Kit$priceAlertsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Kit model
 */
export interface KitFieldRefs {
  readonly id: Prisma.FieldRef<"Kit", 'String'>
  readonly name: Prisma.FieldRef<"Kit", 'String'>
  readonly grade: Prisma.FieldRef<"Kit", 'String'>
  readonly series: Prisma.FieldRef<"Kit", 'String'>
  readonly scale: Prisma.FieldRef<"Kit", 'String'>
  readonly releaseDate: Prisma.FieldRef<"Kit", 'DateTime'>
  readonly imageUrl: Prisma.FieldRef<"Kit", 'String'>
  readonly description: Prisma.FieldRef<"Kit", 'String'>
  readonly createdAt: Prisma.FieldRef<"Kit", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Kit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Kit findUnique
 */
export type KitFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * Filter, which Kit to fetch.
   */
  where: Prisma.KitWhereUniqueInput
}

/**
 * Kit findUniqueOrThrow
 */
export type KitFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * Filter, which Kit to fetch.
   */
  where: Prisma.KitWhereUniqueInput
}

/**
 * Kit findFirst
 */
export type KitFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * Filter, which Kit to fetch.
   */
  where?: Prisma.KitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kits to fetch.
   */
  orderBy?: Prisma.KitOrderByWithRelationInput | Prisma.KitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Kits.
   */
  cursor?: Prisma.KitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kits.
   */
  distinct?: Prisma.KitScalarFieldEnum | Prisma.KitScalarFieldEnum[]
}

/**
 * Kit findFirstOrThrow
 */
export type KitFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * Filter, which Kit to fetch.
   */
  where?: Prisma.KitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kits to fetch.
   */
  orderBy?: Prisma.KitOrderByWithRelationInput | Prisma.KitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Kits.
   */
  cursor?: Prisma.KitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kits.
   */
  distinct?: Prisma.KitScalarFieldEnum | Prisma.KitScalarFieldEnum[]
}

/**
 * Kit findMany
 */
export type KitFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * Filter, which Kits to fetch.
   */
  where?: Prisma.KitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kits to fetch.
   */
  orderBy?: Prisma.KitOrderByWithRelationInput | Prisma.KitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Kits.
   */
  cursor?: Prisma.KitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kits.
   */
  skip?: number
  distinct?: Prisma.KitScalarFieldEnum | Prisma.KitScalarFieldEnum[]
}

/**
 * Kit create
 */
export type KitCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * The data needed to create a Kit.
   */
  data: Prisma.XOR<Prisma.KitCreateInput, Prisma.KitUncheckedCreateInput>
}

/**
 * Kit createMany
 */
export type KitCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Kits.
   */
  data: Prisma.KitCreateManyInput | Prisma.KitCreateManyInput[]
}

/**
 * Kit createManyAndReturn
 */
export type KitCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * The data used to create many Kits.
   */
  data: Prisma.KitCreateManyInput | Prisma.KitCreateManyInput[]
}

/**
 * Kit update
 */
export type KitUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * The data needed to update a Kit.
   */
  data: Prisma.XOR<Prisma.KitUpdateInput, Prisma.KitUncheckedUpdateInput>
  /**
   * Choose, which Kit to update.
   */
  where: Prisma.KitWhereUniqueInput
}

/**
 * Kit updateMany
 */
export type KitUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Kits.
   */
  data: Prisma.XOR<Prisma.KitUpdateManyMutationInput, Prisma.KitUncheckedUpdateManyInput>
  /**
   * Filter which Kits to update
   */
  where?: Prisma.KitWhereInput
  /**
   * Limit how many Kits to update.
   */
  limit?: number
}

/**
 * Kit updateManyAndReturn
 */
export type KitUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * The data used to update Kits.
   */
  data: Prisma.XOR<Prisma.KitUpdateManyMutationInput, Prisma.KitUncheckedUpdateManyInput>
  /**
   * Filter which Kits to update
   */
  where?: Prisma.KitWhereInput
  /**
   * Limit how many Kits to update.
   */
  limit?: number
}

/**
 * Kit upsert
 */
export type KitUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * The filter to search for the Kit to update in case it exists.
   */
  where: Prisma.KitWhereUniqueInput
  /**
   * In case the Kit found by the `where` argument doesn't exist, create a new Kit with this data.
   */
  create: Prisma.XOR<Prisma.KitCreateInput, Prisma.KitUncheckedCreateInput>
  /**
   * In case the Kit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KitUpdateInput, Prisma.KitUncheckedUpdateInput>
}

/**
 * Kit delete
 */
export type KitDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
  /**
   * Filter which Kit to delete.
   */
  where: Prisma.KitWhereUniqueInput
}

/**
 * Kit deleteMany
 */
export type KitDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Kits to delete
   */
  where?: Prisma.KitWhereInput
  /**
   * Limit how many Kits to delete.
   */
  limit?: number
}

/**
 * Kit.priceEntries
 */
export type Kit$priceEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  where?: Prisma.PriceEntryWhereInput
  orderBy?: Prisma.PriceEntryOrderByWithRelationInput | Prisma.PriceEntryOrderByWithRelationInput[]
  cursor?: Prisma.PriceEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PriceEntryScalarFieldEnum | Prisma.PriceEntryScalarFieldEnum[]
}

/**
 * Kit.storeLinks
 */
export type Kit$storeLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  where?: Prisma.StoreLinkWhereInput
  orderBy?: Prisma.StoreLinkOrderByWithRelationInput | Prisma.StoreLinkOrderByWithRelationInput[]
  cursor?: Prisma.StoreLinkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StoreLinkScalarFieldEnum | Prisma.StoreLinkScalarFieldEnum[]
}

/**
 * Kit.wishlistItems
 */
export type Kit$wishlistItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistItem
   */
  select?: Prisma.WishlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WishlistItem
   */
  omit?: Prisma.WishlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WishlistItemInclude<ExtArgs> | null
  where?: Prisma.WishlistItemWhereInput
  orderBy?: Prisma.WishlistItemOrderByWithRelationInput | Prisma.WishlistItemOrderByWithRelationInput[]
  cursor?: Prisma.WishlistItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WishlistItemScalarFieldEnum | Prisma.WishlistItemScalarFieldEnum[]
}

/**
 * Kit.collectionItems
 */
export type Kit$collectionItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CollectionItem
   */
  select?: Prisma.CollectionItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CollectionItem
   */
  omit?: Prisma.CollectionItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollectionItemInclude<ExtArgs> | null
  where?: Prisma.CollectionItemWhereInput
  orderBy?: Prisma.CollectionItemOrderByWithRelationInput | Prisma.CollectionItemOrderByWithRelationInput[]
  cursor?: Prisma.CollectionItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CollectionItemScalarFieldEnum | Prisma.CollectionItemScalarFieldEnum[]
}

/**
 * Kit.priceAlerts
 */
export type Kit$priceAlertsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  where?: Prisma.PriceAlertWhereInput
  orderBy?: Prisma.PriceAlertOrderByWithRelationInput | Prisma.PriceAlertOrderByWithRelationInput[]
  cursor?: Prisma.PriceAlertWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PriceAlertScalarFieldEnum | Prisma.PriceAlertScalarFieldEnum[]
}

/**
 * Kit without action
 */
export type KitDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kit
   */
  select?: Prisma.KitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kit
   */
  omit?: Prisma.KitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitInclude<ExtArgs> | null
}
