
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PriceAlert` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PriceAlert
 * 
 */
export type PriceAlertModel = runtime.Types.Result.DefaultSelection<Prisma.$PriceAlertPayload>

export type AggregatePriceAlert = {
  _count: PriceAlertCountAggregateOutputType | null
  _avg: PriceAlertAvgAggregateOutputType | null
  _sum: PriceAlertSumAggregateOutputType | null
  _min: PriceAlertMinAggregateOutputType | null
  _max: PriceAlertMaxAggregateOutputType | null
}

export type PriceAlertAvgAggregateOutputType = {
  targetPrice: number | null
}

export type PriceAlertSumAggregateOutputType = {
  targetPrice: number | null
}

export type PriceAlertMinAggregateOutputType = {
  id: string | null
  userId: string | null
  kitId: string | null
  targetPrice: number | null
  alertType: string | null
  isActive: boolean | null
  createdAt: Date | null
  triggeredAt: Date | null
}

export type PriceAlertMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  kitId: string | null
  targetPrice: number | null
  alertType: string | null
  isActive: boolean | null
  createdAt: Date | null
  triggeredAt: Date | null
}

export type PriceAlertCountAggregateOutputType = {
  id: number
  userId: number
  kitId: number
  targetPrice: number
  alertType: number
  isActive: number
  createdAt: number
  triggeredAt: number
  _all: number
}


export type PriceAlertAvgAggregateInputType = {
  targetPrice?: true
}

export type PriceAlertSumAggregateInputType = {
  targetPrice?: true
}

export type PriceAlertMinAggregateInputType = {
  id?: true
  userId?: true
  kitId?: true
  targetPrice?: true
  alertType?: true
  isActive?: true
  createdAt?: true
  triggeredAt?: true
}

export type PriceAlertMaxAggregateInputType = {
  id?: true
  userId?: true
  kitId?: true
  targetPrice?: true
  alertType?: true
  isActive?: true
  createdAt?: true
  triggeredAt?: true
}

export type PriceAlertCountAggregateInputType = {
  id?: true
  userId?: true
  kitId?: true
  targetPrice?: true
  alertType?: true
  isActive?: true
  createdAt?: true
  triggeredAt?: true
  _all?: true
}

export type PriceAlertAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceAlert to aggregate.
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceAlerts to fetch.
   */
  orderBy?: Prisma.PriceAlertOrderByWithRelationInput | Prisma.PriceAlertOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PriceAlertWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceAlerts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceAlerts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PriceAlerts
  **/
  _count?: true | PriceAlertCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PriceAlertAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PriceAlertSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PriceAlertMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PriceAlertMaxAggregateInputType
}

export type GetPriceAlertAggregateType<T extends PriceAlertAggregateArgs> = {
      [P in keyof T & keyof AggregatePriceAlert]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePriceAlert[P]>
    : Prisma.GetScalarType<T[P], AggregatePriceAlert[P]>
}




export type PriceAlertGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PriceAlertWhereInput
  orderBy?: Prisma.PriceAlertOrderByWithAggregationInput | Prisma.PriceAlertOrderByWithAggregationInput[]
  by: Prisma.PriceAlertScalarFieldEnum[] | Prisma.PriceAlertScalarFieldEnum
  having?: Prisma.PriceAlertScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PriceAlertCountAggregateInputType | true
  _avg?: PriceAlertAvgAggregateInputType
  _sum?: PriceAlertSumAggregateInputType
  _min?: PriceAlertMinAggregateInputType
  _max?: PriceAlertMaxAggregateInputType
}

export type PriceAlertGroupByOutputType = {
  id: string
  userId: string
  kitId: string
  targetPrice: number | null
  alertType: string
  isActive: boolean
  createdAt: Date
  triggeredAt: Date | null
  _count: PriceAlertCountAggregateOutputType | null
  _avg: PriceAlertAvgAggregateOutputType | null
  _sum: PriceAlertSumAggregateOutputType | null
  _min: PriceAlertMinAggregateOutputType | null
  _max: PriceAlertMaxAggregateOutputType | null
}

type GetPriceAlertGroupByPayload<T extends PriceAlertGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PriceAlertGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PriceAlertGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PriceAlertGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PriceAlertGroupByOutputType[P]>
      }
    >
  >



export type PriceAlertWhereInput = {
  AND?: Prisma.PriceAlertWhereInput | Prisma.PriceAlertWhereInput[]
  OR?: Prisma.PriceAlertWhereInput[]
  NOT?: Prisma.PriceAlertWhereInput | Prisma.PriceAlertWhereInput[]
  id?: Prisma.StringFilter<"PriceAlert"> | string
  userId?: Prisma.StringFilter<"PriceAlert"> | string
  kitId?: Prisma.StringFilter<"PriceAlert"> | string
  targetPrice?: Prisma.FloatNullableFilter<"PriceAlert"> | number | null
  alertType?: Prisma.StringFilter<"PriceAlert"> | string
  isActive?: Prisma.BoolFilter<"PriceAlert"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PriceAlert"> | Date | string
  triggeredAt?: Prisma.DateTimeNullableFilter<"PriceAlert"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  kit?: Prisma.XOR<Prisma.KitScalarRelationFilter, Prisma.KitWhereInput>
}

export type PriceAlertOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  targetPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  alertType?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  triggeredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  kit?: Prisma.KitOrderByWithRelationInput
}

export type PriceAlertWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PriceAlertWhereInput | Prisma.PriceAlertWhereInput[]
  OR?: Prisma.PriceAlertWhereInput[]
  NOT?: Prisma.PriceAlertWhereInput | Prisma.PriceAlertWhereInput[]
  userId?: Prisma.StringFilter<"PriceAlert"> | string
  kitId?: Prisma.StringFilter<"PriceAlert"> | string
  targetPrice?: Prisma.FloatNullableFilter<"PriceAlert"> | number | null
  alertType?: Prisma.StringFilter<"PriceAlert"> | string
  isActive?: Prisma.BoolFilter<"PriceAlert"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PriceAlert"> | Date | string
  triggeredAt?: Prisma.DateTimeNullableFilter<"PriceAlert"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  kit?: Prisma.XOR<Prisma.KitScalarRelationFilter, Prisma.KitWhereInput>
}, "id">

export type PriceAlertOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  targetPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  alertType?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  triggeredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PriceAlertCountOrderByAggregateInput
  _avg?: Prisma.PriceAlertAvgOrderByAggregateInput
  _max?: Prisma.PriceAlertMaxOrderByAggregateInput
  _min?: Prisma.PriceAlertMinOrderByAggregateInput
  _sum?: Prisma.PriceAlertSumOrderByAggregateInput
}

export type PriceAlertScalarWhereWithAggregatesInput = {
  AND?: Prisma.PriceAlertScalarWhereWithAggregatesInput | Prisma.PriceAlertScalarWhereWithAggregatesInput[]
  OR?: Prisma.PriceAlertScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PriceAlertScalarWhereWithAggregatesInput | Prisma.PriceAlertScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PriceAlert"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PriceAlert"> | string
  kitId?: Prisma.StringWithAggregatesFilter<"PriceAlert"> | string
  targetPrice?: Prisma.FloatNullableWithAggregatesFilter<"PriceAlert"> | number | null
  alertType?: Prisma.StringWithAggregatesFilter<"PriceAlert"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"PriceAlert"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PriceAlert"> | Date | string
  triggeredAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PriceAlert"> | Date | string | null
}

export type PriceAlertCreateInput = {
  id?: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutPriceAlertsInput
  kit: Prisma.KitCreateNestedOneWithoutPriceAlertsInput
}

export type PriceAlertUncheckedCreateInput = {
  id?: string
  userId: string
  kitId: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
}

export type PriceAlertUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutPriceAlertsNestedInput
  kit?: Prisma.KitUpdateOneRequiredWithoutPriceAlertsNestedInput
}

export type PriceAlertUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PriceAlertCreateManyInput = {
  id?: string
  userId: string
  kitId: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
}

export type PriceAlertUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PriceAlertUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PriceAlertListRelationFilter = {
  every?: Prisma.PriceAlertWhereInput
  some?: Prisma.PriceAlertWhereInput
  none?: Prisma.PriceAlertWhereInput
}

export type PriceAlertOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PriceAlertCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  targetPrice?: Prisma.SortOrder
  alertType?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  triggeredAt?: Prisma.SortOrder
}

export type PriceAlertAvgOrderByAggregateInput = {
  targetPrice?: Prisma.SortOrder
}

export type PriceAlertMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  targetPrice?: Prisma.SortOrder
  alertType?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  triggeredAt?: Prisma.SortOrder
}

export type PriceAlertMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  targetPrice?: Prisma.SortOrder
  alertType?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  triggeredAt?: Prisma.SortOrder
}

export type PriceAlertSumOrderByAggregateInput = {
  targetPrice?: Prisma.SortOrder
}

export type PriceAlertCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutUserInput, Prisma.PriceAlertUncheckedCreateWithoutUserInput> | Prisma.PriceAlertCreateWithoutUserInput[] | Prisma.PriceAlertUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutUserInput | Prisma.PriceAlertCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PriceAlertCreateManyUserInputEnvelope
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
}

export type PriceAlertUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutUserInput, Prisma.PriceAlertUncheckedCreateWithoutUserInput> | Prisma.PriceAlertCreateWithoutUserInput[] | Prisma.PriceAlertUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutUserInput | Prisma.PriceAlertCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PriceAlertCreateManyUserInputEnvelope
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
}

export type PriceAlertUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutUserInput, Prisma.PriceAlertUncheckedCreateWithoutUserInput> | Prisma.PriceAlertCreateWithoutUserInput[] | Prisma.PriceAlertUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutUserInput | Prisma.PriceAlertCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PriceAlertUpsertWithWhereUniqueWithoutUserInput | Prisma.PriceAlertUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PriceAlertCreateManyUserInputEnvelope
  set?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  disconnect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  delete?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  update?: Prisma.PriceAlertUpdateWithWhereUniqueWithoutUserInput | Prisma.PriceAlertUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PriceAlertUpdateManyWithWhereWithoutUserInput | Prisma.PriceAlertUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PriceAlertScalarWhereInput | Prisma.PriceAlertScalarWhereInput[]
}

export type PriceAlertUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutUserInput, Prisma.PriceAlertUncheckedCreateWithoutUserInput> | Prisma.PriceAlertCreateWithoutUserInput[] | Prisma.PriceAlertUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutUserInput | Prisma.PriceAlertCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PriceAlertUpsertWithWhereUniqueWithoutUserInput | Prisma.PriceAlertUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PriceAlertCreateManyUserInputEnvelope
  set?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  disconnect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  delete?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  update?: Prisma.PriceAlertUpdateWithWhereUniqueWithoutUserInput | Prisma.PriceAlertUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PriceAlertUpdateManyWithWhereWithoutUserInput | Prisma.PriceAlertUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PriceAlertScalarWhereInput | Prisma.PriceAlertScalarWhereInput[]
}

export type PriceAlertCreateNestedManyWithoutKitInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutKitInput, Prisma.PriceAlertUncheckedCreateWithoutKitInput> | Prisma.PriceAlertCreateWithoutKitInput[] | Prisma.PriceAlertUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutKitInput | Prisma.PriceAlertCreateOrConnectWithoutKitInput[]
  createMany?: Prisma.PriceAlertCreateManyKitInputEnvelope
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
}

export type PriceAlertUncheckedCreateNestedManyWithoutKitInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutKitInput, Prisma.PriceAlertUncheckedCreateWithoutKitInput> | Prisma.PriceAlertCreateWithoutKitInput[] | Prisma.PriceAlertUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutKitInput | Prisma.PriceAlertCreateOrConnectWithoutKitInput[]
  createMany?: Prisma.PriceAlertCreateManyKitInputEnvelope
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
}

export type PriceAlertUpdateManyWithoutKitNestedInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutKitInput, Prisma.PriceAlertUncheckedCreateWithoutKitInput> | Prisma.PriceAlertCreateWithoutKitInput[] | Prisma.PriceAlertUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutKitInput | Prisma.PriceAlertCreateOrConnectWithoutKitInput[]
  upsert?: Prisma.PriceAlertUpsertWithWhereUniqueWithoutKitInput | Prisma.PriceAlertUpsertWithWhereUniqueWithoutKitInput[]
  createMany?: Prisma.PriceAlertCreateManyKitInputEnvelope
  set?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  disconnect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  delete?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  update?: Prisma.PriceAlertUpdateWithWhereUniqueWithoutKitInput | Prisma.PriceAlertUpdateWithWhereUniqueWithoutKitInput[]
  updateMany?: Prisma.PriceAlertUpdateManyWithWhereWithoutKitInput | Prisma.PriceAlertUpdateManyWithWhereWithoutKitInput[]
  deleteMany?: Prisma.PriceAlertScalarWhereInput | Prisma.PriceAlertScalarWhereInput[]
}

export type PriceAlertUncheckedUpdateManyWithoutKitNestedInput = {
  create?: Prisma.XOR<Prisma.PriceAlertCreateWithoutKitInput, Prisma.PriceAlertUncheckedCreateWithoutKitInput> | Prisma.PriceAlertCreateWithoutKitInput[] | Prisma.PriceAlertUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceAlertCreateOrConnectWithoutKitInput | Prisma.PriceAlertCreateOrConnectWithoutKitInput[]
  upsert?: Prisma.PriceAlertUpsertWithWhereUniqueWithoutKitInput | Prisma.PriceAlertUpsertWithWhereUniqueWithoutKitInput[]
  createMany?: Prisma.PriceAlertCreateManyKitInputEnvelope
  set?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  disconnect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  delete?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  connect?: Prisma.PriceAlertWhereUniqueInput | Prisma.PriceAlertWhereUniqueInput[]
  update?: Prisma.PriceAlertUpdateWithWhereUniqueWithoutKitInput | Prisma.PriceAlertUpdateWithWhereUniqueWithoutKitInput[]
  updateMany?: Prisma.PriceAlertUpdateManyWithWhereWithoutKitInput | Prisma.PriceAlertUpdateManyWithWhereWithoutKitInput[]
  deleteMany?: Prisma.PriceAlertScalarWhereInput | Prisma.PriceAlertScalarWhereInput[]
}

export type PriceAlertCreateWithoutUserInput = {
  id?: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
  kit: Prisma.KitCreateNestedOneWithoutPriceAlertsInput
}

export type PriceAlertUncheckedCreateWithoutUserInput = {
  id?: string
  kitId: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
}

export type PriceAlertCreateOrConnectWithoutUserInput = {
  where: Prisma.PriceAlertWhereUniqueInput
  create: Prisma.XOR<Prisma.PriceAlertCreateWithoutUserInput, Prisma.PriceAlertUncheckedCreateWithoutUserInput>
}

export type PriceAlertCreateManyUserInputEnvelope = {
  data: Prisma.PriceAlertCreateManyUserInput | Prisma.PriceAlertCreateManyUserInput[]
}

export type PriceAlertUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PriceAlertWhereUniqueInput
  update: Prisma.XOR<Prisma.PriceAlertUpdateWithoutUserInput, Prisma.PriceAlertUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PriceAlertCreateWithoutUserInput, Prisma.PriceAlertUncheckedCreateWithoutUserInput>
}

export type PriceAlertUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PriceAlertWhereUniqueInput
  data: Prisma.XOR<Prisma.PriceAlertUpdateWithoutUserInput, Prisma.PriceAlertUncheckedUpdateWithoutUserInput>
}

export type PriceAlertUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PriceAlertScalarWhereInput
  data: Prisma.XOR<Prisma.PriceAlertUpdateManyMutationInput, Prisma.PriceAlertUncheckedUpdateManyWithoutUserInput>
}

export type PriceAlertScalarWhereInput = {
  AND?: Prisma.PriceAlertScalarWhereInput | Prisma.PriceAlertScalarWhereInput[]
  OR?: Prisma.PriceAlertScalarWhereInput[]
  NOT?: Prisma.PriceAlertScalarWhereInput | Prisma.PriceAlertScalarWhereInput[]
  id?: Prisma.StringFilter<"PriceAlert"> | string
  userId?: Prisma.StringFilter<"PriceAlert"> | string
  kitId?: Prisma.StringFilter<"PriceAlert"> | string
  targetPrice?: Prisma.FloatNullableFilter<"PriceAlert"> | number | null
  alertType?: Prisma.StringFilter<"PriceAlert"> | string
  isActive?: Prisma.BoolFilter<"PriceAlert"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PriceAlert"> | Date | string
  triggeredAt?: Prisma.DateTimeNullableFilter<"PriceAlert"> | Date | string | null
}

export type PriceAlertCreateWithoutKitInput = {
  id?: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutPriceAlertsInput
}

export type PriceAlertUncheckedCreateWithoutKitInput = {
  id?: string
  userId: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
}

export type PriceAlertCreateOrConnectWithoutKitInput = {
  where: Prisma.PriceAlertWhereUniqueInput
  create: Prisma.XOR<Prisma.PriceAlertCreateWithoutKitInput, Prisma.PriceAlertUncheckedCreateWithoutKitInput>
}

export type PriceAlertCreateManyKitInputEnvelope = {
  data: Prisma.PriceAlertCreateManyKitInput | Prisma.PriceAlertCreateManyKitInput[]
}

export type PriceAlertUpsertWithWhereUniqueWithoutKitInput = {
  where: Prisma.PriceAlertWhereUniqueInput
  update: Prisma.XOR<Prisma.PriceAlertUpdateWithoutKitInput, Prisma.PriceAlertUncheckedUpdateWithoutKitInput>
  create: Prisma.XOR<Prisma.PriceAlertCreateWithoutKitInput, Prisma.PriceAlertUncheckedCreateWithoutKitInput>
}

export type PriceAlertUpdateWithWhereUniqueWithoutKitInput = {
  where: Prisma.PriceAlertWhereUniqueInput
  data: Prisma.XOR<Prisma.PriceAlertUpdateWithoutKitInput, Prisma.PriceAlertUncheckedUpdateWithoutKitInput>
}

export type PriceAlertUpdateManyWithWhereWithoutKitInput = {
  where: Prisma.PriceAlertScalarWhereInput
  data: Prisma.XOR<Prisma.PriceAlertUpdateManyMutationInput, Prisma.PriceAlertUncheckedUpdateManyWithoutKitInput>
}

export type PriceAlertCreateManyUserInput = {
  id?: string
  kitId: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
}

export type PriceAlertUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kit?: Prisma.KitUpdateOneRequiredWithoutPriceAlertsNestedInput
}

export type PriceAlertUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PriceAlertUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PriceAlertCreateManyKitInput = {
  id?: string
  userId: string
  targetPrice?: number | null
  alertType: string
  isActive?: boolean
  createdAt?: Date | string
  triggeredAt?: Date | string | null
}

export type PriceAlertUpdateWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutPriceAlertsNestedInput
}

export type PriceAlertUncheckedUpdateWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PriceAlertUncheckedUpdateManyWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  targetPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  alertType?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  triggeredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type PriceAlertSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kitId?: boolean
  targetPrice?: boolean
  alertType?: boolean
  isActive?: boolean
  createdAt?: boolean
  triggeredAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceAlert"]>

export type PriceAlertSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kitId?: boolean
  targetPrice?: boolean
  alertType?: boolean
  isActive?: boolean
  createdAt?: boolean
  triggeredAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceAlert"]>

export type PriceAlertSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kitId?: boolean
  targetPrice?: boolean
  alertType?: boolean
  isActive?: boolean
  createdAt?: boolean
  triggeredAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceAlert"]>

export type PriceAlertSelectScalar = {
  id?: boolean
  userId?: boolean
  kitId?: boolean
  targetPrice?: boolean
  alertType?: boolean
  isActive?: boolean
  createdAt?: boolean
  triggeredAt?: boolean
}

export type PriceAlertOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "kitId" | "targetPrice" | "alertType" | "isActive" | "createdAt" | "triggeredAt", ExtArgs["result"]["priceAlert"]>
export type PriceAlertInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}
export type PriceAlertIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}
export type PriceAlertIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}

export type $PriceAlertPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PriceAlert"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    kit: Prisma.$KitPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    kitId: string
    targetPrice: number | null
    alertType: string
    isActive: boolean
    createdAt: Date
    triggeredAt: Date | null
  }, ExtArgs["result"]["priceAlert"]>
  composites: {}
}

export type PriceAlertGetPayload<S extends boolean | null | undefined | PriceAlertDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload, S>

export type PriceAlertCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PriceAlertFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PriceAlertCountAggregateInputType | true
  }

export interface PriceAlertDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PriceAlert'], meta: { name: 'PriceAlert' } }
  /**
   * Find zero or one PriceAlert that matches the filter.
   * @param {PriceAlertFindUniqueArgs} args - Arguments to find a PriceAlert
   * @example
   * // Get one PriceAlert
   * const priceAlert = await prisma.priceAlert.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PriceAlertFindUniqueArgs>(args: Prisma.SelectSubset<T, PriceAlertFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PriceAlert that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PriceAlertFindUniqueOrThrowArgs} args - Arguments to find a PriceAlert
   * @example
   * // Get one PriceAlert
   * const priceAlert = await prisma.priceAlert.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PriceAlertFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PriceAlertFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceAlert that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertFindFirstArgs} args - Arguments to find a PriceAlert
   * @example
   * // Get one PriceAlert
   * const priceAlert = await prisma.priceAlert.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PriceAlertFindFirstArgs>(args?: Prisma.SelectSubset<T, PriceAlertFindFirstArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceAlert that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertFindFirstOrThrowArgs} args - Arguments to find a PriceAlert
   * @example
   * // Get one PriceAlert
   * const priceAlert = await prisma.priceAlert.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PriceAlertFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PriceAlertFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PriceAlerts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PriceAlerts
   * const priceAlerts = await prisma.priceAlert.findMany()
   * 
   * // Get first 10 PriceAlerts
   * const priceAlerts = await prisma.priceAlert.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const priceAlertWithIdOnly = await prisma.priceAlert.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PriceAlertFindManyArgs>(args?: Prisma.SelectSubset<T, PriceAlertFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PriceAlert.
   * @param {PriceAlertCreateArgs} args - Arguments to create a PriceAlert.
   * @example
   * // Create one PriceAlert
   * const PriceAlert = await prisma.priceAlert.create({
   *   data: {
   *     // ... data to create a PriceAlert
   *   }
   * })
   * 
   */
  create<T extends PriceAlertCreateArgs>(args: Prisma.SelectSubset<T, PriceAlertCreateArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PriceAlerts.
   * @param {PriceAlertCreateManyArgs} args - Arguments to create many PriceAlerts.
   * @example
   * // Create many PriceAlerts
   * const priceAlert = await prisma.priceAlert.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PriceAlertCreateManyArgs>(args?: Prisma.SelectSubset<T, PriceAlertCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PriceAlerts and returns the data saved in the database.
   * @param {PriceAlertCreateManyAndReturnArgs} args - Arguments to create many PriceAlerts.
   * @example
   * // Create many PriceAlerts
   * const priceAlert = await prisma.priceAlert.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PriceAlerts and only return the `id`
   * const priceAlertWithIdOnly = await prisma.priceAlert.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PriceAlertCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PriceAlertCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PriceAlert.
   * @param {PriceAlertDeleteArgs} args - Arguments to delete one PriceAlert.
   * @example
   * // Delete one PriceAlert
   * const PriceAlert = await prisma.priceAlert.delete({
   *   where: {
   *     // ... filter to delete one PriceAlert
   *   }
   * })
   * 
   */
  delete<T extends PriceAlertDeleteArgs>(args: Prisma.SelectSubset<T, PriceAlertDeleteArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PriceAlert.
   * @param {PriceAlertUpdateArgs} args - Arguments to update one PriceAlert.
   * @example
   * // Update one PriceAlert
   * const priceAlert = await prisma.priceAlert.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PriceAlertUpdateArgs>(args: Prisma.SelectSubset<T, PriceAlertUpdateArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PriceAlerts.
   * @param {PriceAlertDeleteManyArgs} args - Arguments to filter PriceAlerts to delete.
   * @example
   * // Delete a few PriceAlerts
   * const { count } = await prisma.priceAlert.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PriceAlertDeleteManyArgs>(args?: Prisma.SelectSubset<T, PriceAlertDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceAlerts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PriceAlerts
   * const priceAlert = await prisma.priceAlert.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PriceAlertUpdateManyArgs>(args: Prisma.SelectSubset<T, PriceAlertUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceAlerts and returns the data updated in the database.
   * @param {PriceAlertUpdateManyAndReturnArgs} args - Arguments to update many PriceAlerts.
   * @example
   * // Update many PriceAlerts
   * const priceAlert = await prisma.priceAlert.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PriceAlerts and only return the `id`
   * const priceAlertWithIdOnly = await prisma.priceAlert.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PriceAlertUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PriceAlertUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PriceAlert.
   * @param {PriceAlertUpsertArgs} args - Arguments to update or create a PriceAlert.
   * @example
   * // Update or create a PriceAlert
   * const priceAlert = await prisma.priceAlert.upsert({
   *   create: {
   *     // ... data to create a PriceAlert
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PriceAlert we want to update
   *   }
   * })
   */
  upsert<T extends PriceAlertUpsertArgs>(args: Prisma.SelectSubset<T, PriceAlertUpsertArgs<ExtArgs>>): Prisma.Prisma__PriceAlertClient<runtime.Types.Result.GetResult<Prisma.$PriceAlertPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PriceAlerts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertCountArgs} args - Arguments to filter PriceAlerts to count.
   * @example
   * // Count the number of PriceAlerts
   * const count = await prisma.priceAlert.count({
   *   where: {
   *     // ... the filter for the PriceAlerts we want to count
   *   }
   * })
  **/
  count<T extends PriceAlertCountArgs>(
    args?: Prisma.Subset<T, PriceAlertCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PriceAlertCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PriceAlert.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PriceAlertAggregateArgs>(args: Prisma.Subset<T, PriceAlertAggregateArgs>): Prisma.PrismaPromise<GetPriceAlertAggregateType<T>>

  /**
   * Group by PriceAlert.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceAlertGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PriceAlertGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PriceAlertGroupByArgs['orderBy'] }
      : { orderBy?: PriceAlertGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PriceAlertGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPriceAlertGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PriceAlert model
 */
readonly fields: PriceAlertFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PriceAlert.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PriceAlertClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  kit<T extends Prisma.KitDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KitDefaultArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PriceAlert model
 */
export interface PriceAlertFieldRefs {
  readonly id: Prisma.FieldRef<"PriceAlert", 'String'>
  readonly userId: Prisma.FieldRef<"PriceAlert", 'String'>
  readonly kitId: Prisma.FieldRef<"PriceAlert", 'String'>
  readonly targetPrice: Prisma.FieldRef<"PriceAlert", 'Float'>
  readonly alertType: Prisma.FieldRef<"PriceAlert", 'String'>
  readonly isActive: Prisma.FieldRef<"PriceAlert", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PriceAlert", 'DateTime'>
  readonly triggeredAt: Prisma.FieldRef<"PriceAlert", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PriceAlert findUnique
 */
export type PriceAlertFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * Filter, which PriceAlert to fetch.
   */
  where: Prisma.PriceAlertWhereUniqueInput
}

/**
 * PriceAlert findUniqueOrThrow
 */
export type PriceAlertFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * Filter, which PriceAlert to fetch.
   */
  where: Prisma.PriceAlertWhereUniqueInput
}

/**
 * PriceAlert findFirst
 */
export type PriceAlertFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * Filter, which PriceAlert to fetch.
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceAlerts to fetch.
   */
  orderBy?: Prisma.PriceAlertOrderByWithRelationInput | Prisma.PriceAlertOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceAlerts.
   */
  cursor?: Prisma.PriceAlertWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceAlerts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceAlerts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceAlerts.
   */
  distinct?: Prisma.PriceAlertScalarFieldEnum | Prisma.PriceAlertScalarFieldEnum[]
}

/**
 * PriceAlert findFirstOrThrow
 */
export type PriceAlertFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * Filter, which PriceAlert to fetch.
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceAlerts to fetch.
   */
  orderBy?: Prisma.PriceAlertOrderByWithRelationInput | Prisma.PriceAlertOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceAlerts.
   */
  cursor?: Prisma.PriceAlertWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceAlerts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceAlerts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceAlerts.
   */
  distinct?: Prisma.PriceAlertScalarFieldEnum | Prisma.PriceAlertScalarFieldEnum[]
}

/**
 * PriceAlert findMany
 */
export type PriceAlertFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * Filter, which PriceAlerts to fetch.
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceAlerts to fetch.
   */
  orderBy?: Prisma.PriceAlertOrderByWithRelationInput | Prisma.PriceAlertOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PriceAlerts.
   */
  cursor?: Prisma.PriceAlertWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceAlerts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceAlerts.
   */
  skip?: number
  distinct?: Prisma.PriceAlertScalarFieldEnum | Prisma.PriceAlertScalarFieldEnum[]
}

/**
 * PriceAlert create
 */
export type PriceAlertCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * The data needed to create a PriceAlert.
   */
  data: Prisma.XOR<Prisma.PriceAlertCreateInput, Prisma.PriceAlertUncheckedCreateInput>
}

/**
 * PriceAlert createMany
 */
export type PriceAlertCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PriceAlerts.
   */
  data: Prisma.PriceAlertCreateManyInput | Prisma.PriceAlertCreateManyInput[]
}

/**
 * PriceAlert createManyAndReturn
 */
export type PriceAlertCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * The data used to create many PriceAlerts.
   */
  data: Prisma.PriceAlertCreateManyInput | Prisma.PriceAlertCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PriceAlert update
 */
export type PriceAlertUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * The data needed to update a PriceAlert.
   */
  data: Prisma.XOR<Prisma.PriceAlertUpdateInput, Prisma.PriceAlertUncheckedUpdateInput>
  /**
   * Choose, which PriceAlert to update.
   */
  where: Prisma.PriceAlertWhereUniqueInput
}

/**
 * PriceAlert updateMany
 */
export type PriceAlertUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PriceAlerts.
   */
  data: Prisma.XOR<Prisma.PriceAlertUpdateManyMutationInput, Prisma.PriceAlertUncheckedUpdateManyInput>
  /**
   * Filter which PriceAlerts to update
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * Limit how many PriceAlerts to update.
   */
  limit?: number
}

/**
 * PriceAlert updateManyAndReturn
 */
export type PriceAlertUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * The data used to update PriceAlerts.
   */
  data: Prisma.XOR<Prisma.PriceAlertUpdateManyMutationInput, Prisma.PriceAlertUncheckedUpdateManyInput>
  /**
   * Filter which PriceAlerts to update
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * Limit how many PriceAlerts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PriceAlert upsert
 */
export type PriceAlertUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * The filter to search for the PriceAlert to update in case it exists.
   */
  where: Prisma.PriceAlertWhereUniqueInput
  /**
   * In case the PriceAlert found by the `where` argument doesn't exist, create a new PriceAlert with this data.
   */
  create: Prisma.XOR<Prisma.PriceAlertCreateInput, Prisma.PriceAlertUncheckedCreateInput>
  /**
   * In case the PriceAlert was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PriceAlertUpdateInput, Prisma.PriceAlertUncheckedUpdateInput>
}

/**
 * PriceAlert delete
 */
export type PriceAlertDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
  /**
   * Filter which PriceAlert to delete.
   */
  where: Prisma.PriceAlertWhereUniqueInput
}

/**
 * PriceAlert deleteMany
 */
export type PriceAlertDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceAlerts to delete
   */
  where?: Prisma.PriceAlertWhereInput
  /**
   * Limit how many PriceAlerts to delete.
   */
  limit?: number
}

/**
 * PriceAlert without action
 */
export type PriceAlertDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAlert
   */
  select?: Prisma.PriceAlertSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAlert
   */
  omit?: Prisma.PriceAlertOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceAlertInclude<ExtArgs> | null
}
