
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PriceEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PriceEntry
 * 
 */
export type PriceEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$PriceEntryPayload>

export type AggregatePriceEntry = {
  _count: PriceEntryCountAggregateOutputType | null
  _avg: PriceEntryAvgAggregateOutputType | null
  _sum: PriceEntrySumAggregateOutputType | null
  _min: PriceEntryMinAggregateOutputType | null
  _max: PriceEntryMaxAggregateOutputType | null
}

export type PriceEntryAvgAggregateOutputType = {
  price: number | null
}

export type PriceEntrySumAggregateOutputType = {
  price: number | null
}

export type PriceEntryMinAggregateOutputType = {
  id: string | null
  kitId: string | null
  storeId: string | null
  price: number | null
  currency: string | null
  inStock: boolean | null
  recordedAt: Date | null
}

export type PriceEntryMaxAggregateOutputType = {
  id: string | null
  kitId: string | null
  storeId: string | null
  price: number | null
  currency: string | null
  inStock: boolean | null
  recordedAt: Date | null
}

export type PriceEntryCountAggregateOutputType = {
  id: number
  kitId: number
  storeId: number
  price: number
  currency: number
  inStock: number
  recordedAt: number
  _all: number
}


export type PriceEntryAvgAggregateInputType = {
  price?: true
}

export type PriceEntrySumAggregateInputType = {
  price?: true
}

export type PriceEntryMinAggregateInputType = {
  id?: true
  kitId?: true
  storeId?: true
  price?: true
  currency?: true
  inStock?: true
  recordedAt?: true
}

export type PriceEntryMaxAggregateInputType = {
  id?: true
  kitId?: true
  storeId?: true
  price?: true
  currency?: true
  inStock?: true
  recordedAt?: true
}

export type PriceEntryCountAggregateInputType = {
  id?: true
  kitId?: true
  storeId?: true
  price?: true
  currency?: true
  inStock?: true
  recordedAt?: true
  _all?: true
}

export type PriceEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceEntry to aggregate.
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceEntries to fetch.
   */
  orderBy?: Prisma.PriceEntryOrderByWithRelationInput | Prisma.PriceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PriceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PriceEntries
  **/
  _count?: true | PriceEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PriceEntryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PriceEntrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PriceEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PriceEntryMaxAggregateInputType
}

export type GetPriceEntryAggregateType<T extends PriceEntryAggregateArgs> = {
      [P in keyof T & keyof AggregatePriceEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePriceEntry[P]>
    : Prisma.GetScalarType<T[P], AggregatePriceEntry[P]>
}




export type PriceEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PriceEntryWhereInput
  orderBy?: Prisma.PriceEntryOrderByWithAggregationInput | Prisma.PriceEntryOrderByWithAggregationInput[]
  by: Prisma.PriceEntryScalarFieldEnum[] | Prisma.PriceEntryScalarFieldEnum
  having?: Prisma.PriceEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PriceEntryCountAggregateInputType | true
  _avg?: PriceEntryAvgAggregateInputType
  _sum?: PriceEntrySumAggregateInputType
  _min?: PriceEntryMinAggregateInputType
  _max?: PriceEntryMaxAggregateInputType
}

export type PriceEntryGroupByOutputType = {
  id: string
  kitId: string
  storeId: string | null
  price: number
  currency: string
  inStock: boolean
  recordedAt: Date
  _count: PriceEntryCountAggregateOutputType | null
  _avg: PriceEntryAvgAggregateOutputType | null
  _sum: PriceEntrySumAggregateOutputType | null
  _min: PriceEntryMinAggregateOutputType | null
  _max: PriceEntryMaxAggregateOutputType | null
}

type GetPriceEntryGroupByPayload<T extends PriceEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PriceEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PriceEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PriceEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PriceEntryGroupByOutputType[P]>
      }
    >
  >



export type PriceEntryWhereInput = {
  AND?: Prisma.PriceEntryWhereInput | Prisma.PriceEntryWhereInput[]
  OR?: Prisma.PriceEntryWhereInput[]
  NOT?: Prisma.PriceEntryWhereInput | Prisma.PriceEntryWhereInput[]
  id?: Prisma.StringFilter<"PriceEntry"> | string
  kitId?: Prisma.StringFilter<"PriceEntry"> | string
  storeId?: Prisma.StringNullableFilter<"PriceEntry"> | string | null
  price?: Prisma.FloatFilter<"PriceEntry"> | number
  currency?: Prisma.StringFilter<"PriceEntry"> | string
  inStock?: Prisma.BoolFilter<"PriceEntry"> | boolean
  recordedAt?: Prisma.DateTimeFilter<"PriceEntry"> | Date | string
  kit?: Prisma.XOR<Prisma.KitScalarRelationFilter, Prisma.KitWhereInput>
}

export type PriceEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrderInput | Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  inStock?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  kit?: Prisma.KitOrderByWithRelationInput
}

export type PriceEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PriceEntryWhereInput | Prisma.PriceEntryWhereInput[]
  OR?: Prisma.PriceEntryWhereInput[]
  NOT?: Prisma.PriceEntryWhereInput | Prisma.PriceEntryWhereInput[]
  kitId?: Prisma.StringFilter<"PriceEntry"> | string
  storeId?: Prisma.StringNullableFilter<"PriceEntry"> | string | null
  price?: Prisma.FloatFilter<"PriceEntry"> | number
  currency?: Prisma.StringFilter<"PriceEntry"> | string
  inStock?: Prisma.BoolFilter<"PriceEntry"> | boolean
  recordedAt?: Prisma.DateTimeFilter<"PriceEntry"> | Date | string
  kit?: Prisma.XOR<Prisma.KitScalarRelationFilter, Prisma.KitWhereInput>
}, "id">

export type PriceEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrderInput | Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  inStock?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  _count?: Prisma.PriceEntryCountOrderByAggregateInput
  _avg?: Prisma.PriceEntryAvgOrderByAggregateInput
  _max?: Prisma.PriceEntryMaxOrderByAggregateInput
  _min?: Prisma.PriceEntryMinOrderByAggregateInput
  _sum?: Prisma.PriceEntrySumOrderByAggregateInput
}

export type PriceEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.PriceEntryScalarWhereWithAggregatesInput | Prisma.PriceEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.PriceEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PriceEntryScalarWhereWithAggregatesInput | Prisma.PriceEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PriceEntry"> | string
  kitId?: Prisma.StringWithAggregatesFilter<"PriceEntry"> | string
  storeId?: Prisma.StringNullableWithAggregatesFilter<"PriceEntry"> | string | null
  price?: Prisma.FloatWithAggregatesFilter<"PriceEntry"> | number
  currency?: Prisma.StringWithAggregatesFilter<"PriceEntry"> | string
  inStock?: Prisma.BoolWithAggregatesFilter<"PriceEntry"> | boolean
  recordedAt?: Prisma.DateTimeWithAggregatesFilter<"PriceEntry"> | Date | string
}

export type PriceEntryCreateInput = {
  id?: string
  storeId?: string | null
  price: number
  currency?: string
  inStock?: boolean
  recordedAt?: Date | string
  kit: Prisma.KitCreateNestedOneWithoutPriceEntriesInput
}

export type PriceEntryUncheckedCreateInput = {
  id?: string
  kitId: string
  storeId?: string | null
  price: number
  currency?: string
  inStock?: boolean
  recordedAt?: Date | string
}

export type PriceEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kit?: Prisma.KitUpdateOneRequiredWithoutPriceEntriesNestedInput
}

export type PriceEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceEntryCreateManyInput = {
  id?: string
  kitId: string
  storeId?: string | null
  price: number
  currency?: string
  inStock?: boolean
  recordedAt?: Date | string
}

export type PriceEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceEntryListRelationFilter = {
  every?: Prisma.PriceEntryWhereInput
  some?: Prisma.PriceEntryWhereInput
  none?: Prisma.PriceEntryWhereInput
}

export type PriceEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PriceEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  inStock?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type PriceEntryAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type PriceEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  inStock?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type PriceEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  inStock?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type PriceEntrySumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type PriceEntryCreateNestedManyWithoutKitInput = {
  create?: Prisma.XOR<Prisma.PriceEntryCreateWithoutKitInput, Prisma.PriceEntryUncheckedCreateWithoutKitInput> | Prisma.PriceEntryCreateWithoutKitInput[] | Prisma.PriceEntryUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceEntryCreateOrConnectWithoutKitInput | Prisma.PriceEntryCreateOrConnectWithoutKitInput[]
  createMany?: Prisma.PriceEntryCreateManyKitInputEnvelope
  connect?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
}

export type PriceEntryUncheckedCreateNestedManyWithoutKitInput = {
  create?: Prisma.XOR<Prisma.PriceEntryCreateWithoutKitInput, Prisma.PriceEntryUncheckedCreateWithoutKitInput> | Prisma.PriceEntryCreateWithoutKitInput[] | Prisma.PriceEntryUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceEntryCreateOrConnectWithoutKitInput | Prisma.PriceEntryCreateOrConnectWithoutKitInput[]
  createMany?: Prisma.PriceEntryCreateManyKitInputEnvelope
  connect?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
}

export type PriceEntryUpdateManyWithoutKitNestedInput = {
  create?: Prisma.XOR<Prisma.PriceEntryCreateWithoutKitInput, Prisma.PriceEntryUncheckedCreateWithoutKitInput> | Prisma.PriceEntryCreateWithoutKitInput[] | Prisma.PriceEntryUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceEntryCreateOrConnectWithoutKitInput | Prisma.PriceEntryCreateOrConnectWithoutKitInput[]
  upsert?: Prisma.PriceEntryUpsertWithWhereUniqueWithoutKitInput | Prisma.PriceEntryUpsertWithWhereUniqueWithoutKitInput[]
  createMany?: Prisma.PriceEntryCreateManyKitInputEnvelope
  set?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  disconnect?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  delete?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  connect?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  update?: Prisma.PriceEntryUpdateWithWhereUniqueWithoutKitInput | Prisma.PriceEntryUpdateWithWhereUniqueWithoutKitInput[]
  updateMany?: Prisma.PriceEntryUpdateManyWithWhereWithoutKitInput | Prisma.PriceEntryUpdateManyWithWhereWithoutKitInput[]
  deleteMany?: Prisma.PriceEntryScalarWhereInput | Prisma.PriceEntryScalarWhereInput[]
}

export type PriceEntryUncheckedUpdateManyWithoutKitNestedInput = {
  create?: Prisma.XOR<Prisma.PriceEntryCreateWithoutKitInput, Prisma.PriceEntryUncheckedCreateWithoutKitInput> | Prisma.PriceEntryCreateWithoutKitInput[] | Prisma.PriceEntryUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.PriceEntryCreateOrConnectWithoutKitInput | Prisma.PriceEntryCreateOrConnectWithoutKitInput[]
  upsert?: Prisma.PriceEntryUpsertWithWhereUniqueWithoutKitInput | Prisma.PriceEntryUpsertWithWhereUniqueWithoutKitInput[]
  createMany?: Prisma.PriceEntryCreateManyKitInputEnvelope
  set?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  disconnect?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  delete?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  connect?: Prisma.PriceEntryWhereUniqueInput | Prisma.PriceEntryWhereUniqueInput[]
  update?: Prisma.PriceEntryUpdateWithWhereUniqueWithoutKitInput | Prisma.PriceEntryUpdateWithWhereUniqueWithoutKitInput[]
  updateMany?: Prisma.PriceEntryUpdateManyWithWhereWithoutKitInput | Prisma.PriceEntryUpdateManyWithWhereWithoutKitInput[]
  deleteMany?: Prisma.PriceEntryScalarWhereInput | Prisma.PriceEntryScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PriceEntryCreateWithoutKitInput = {
  id?: string
  storeId?: string | null
  price: number
  currency?: string
  inStock?: boolean
  recordedAt?: Date | string
}

export type PriceEntryUncheckedCreateWithoutKitInput = {
  id?: string
  storeId?: string | null
  price: number
  currency?: string
  inStock?: boolean
  recordedAt?: Date | string
}

export type PriceEntryCreateOrConnectWithoutKitInput = {
  where: Prisma.PriceEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.PriceEntryCreateWithoutKitInput, Prisma.PriceEntryUncheckedCreateWithoutKitInput>
}

export type PriceEntryCreateManyKitInputEnvelope = {
  data: Prisma.PriceEntryCreateManyKitInput | Prisma.PriceEntryCreateManyKitInput[]
}

export type PriceEntryUpsertWithWhereUniqueWithoutKitInput = {
  where: Prisma.PriceEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.PriceEntryUpdateWithoutKitInput, Prisma.PriceEntryUncheckedUpdateWithoutKitInput>
  create: Prisma.XOR<Prisma.PriceEntryCreateWithoutKitInput, Prisma.PriceEntryUncheckedCreateWithoutKitInput>
}

export type PriceEntryUpdateWithWhereUniqueWithoutKitInput = {
  where: Prisma.PriceEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.PriceEntryUpdateWithoutKitInput, Prisma.PriceEntryUncheckedUpdateWithoutKitInput>
}

export type PriceEntryUpdateManyWithWhereWithoutKitInput = {
  where: Prisma.PriceEntryScalarWhereInput
  data: Prisma.XOR<Prisma.PriceEntryUpdateManyMutationInput, Prisma.PriceEntryUncheckedUpdateManyWithoutKitInput>
}

export type PriceEntryScalarWhereInput = {
  AND?: Prisma.PriceEntryScalarWhereInput | Prisma.PriceEntryScalarWhereInput[]
  OR?: Prisma.PriceEntryScalarWhereInput[]
  NOT?: Prisma.PriceEntryScalarWhereInput | Prisma.PriceEntryScalarWhereInput[]
  id?: Prisma.StringFilter<"PriceEntry"> | string
  kitId?: Prisma.StringFilter<"PriceEntry"> | string
  storeId?: Prisma.StringNullableFilter<"PriceEntry"> | string | null
  price?: Prisma.FloatFilter<"PriceEntry"> | number
  currency?: Prisma.StringFilter<"PriceEntry"> | string
  inStock?: Prisma.BoolFilter<"PriceEntry"> | boolean
  recordedAt?: Prisma.DateTimeFilter<"PriceEntry"> | Date | string
}

export type PriceEntryCreateManyKitInput = {
  id?: string
  storeId?: string | null
  price: number
  currency?: string
  inStock?: boolean
  recordedAt?: Date | string
}

export type PriceEntryUpdateWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceEntryUncheckedUpdateWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PriceEntryUncheckedUpdateManyWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  inStock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PriceEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  price?: boolean
  currency?: boolean
  inStock?: boolean
  recordedAt?: boolean
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceEntry"]>

export type PriceEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  price?: boolean
  currency?: boolean
  inStock?: boolean
  recordedAt?: boolean
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceEntry"]>

export type PriceEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  price?: boolean
  currency?: boolean
  inStock?: boolean
  recordedAt?: boolean
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["priceEntry"]>

export type PriceEntrySelectScalar = {
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  price?: boolean
  currency?: boolean
  inStock?: boolean
  recordedAt?: boolean
}

export type PriceEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "kitId" | "storeId" | "price" | "currency" | "inStock" | "recordedAt", ExtArgs["result"]["priceEntry"]>
export type PriceEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}
export type PriceEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}
export type PriceEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
}

export type $PriceEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PriceEntry"
  objects: {
    kit: Prisma.$KitPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    kitId: string
    storeId: string | null
    price: number
    currency: string
    inStock: boolean
    recordedAt: Date
  }, ExtArgs["result"]["priceEntry"]>
  composites: {}
}

export type PriceEntryGetPayload<S extends boolean | null | undefined | PriceEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload, S>

export type PriceEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PriceEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PriceEntryCountAggregateInputType | true
  }

export interface PriceEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PriceEntry'], meta: { name: 'PriceEntry' } }
  /**
   * Find zero or one PriceEntry that matches the filter.
   * @param {PriceEntryFindUniqueArgs} args - Arguments to find a PriceEntry
   * @example
   * // Get one PriceEntry
   * const priceEntry = await prisma.priceEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PriceEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, PriceEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PriceEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PriceEntryFindUniqueOrThrowArgs} args - Arguments to find a PriceEntry
   * @example
   * // Get one PriceEntry
   * const priceEntry = await prisma.priceEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PriceEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PriceEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryFindFirstArgs} args - Arguments to find a PriceEntry
   * @example
   * // Get one PriceEntry
   * const priceEntry = await prisma.priceEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PriceEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, PriceEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PriceEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryFindFirstOrThrowArgs} args - Arguments to find a PriceEntry
   * @example
   * // Get one PriceEntry
   * const priceEntry = await prisma.priceEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PriceEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PriceEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PriceEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PriceEntries
   * const priceEntries = await prisma.priceEntry.findMany()
   * 
   * // Get first 10 PriceEntries
   * const priceEntries = await prisma.priceEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const priceEntryWithIdOnly = await prisma.priceEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PriceEntryFindManyArgs>(args?: Prisma.SelectSubset<T, PriceEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PriceEntry.
   * @param {PriceEntryCreateArgs} args - Arguments to create a PriceEntry.
   * @example
   * // Create one PriceEntry
   * const PriceEntry = await prisma.priceEntry.create({
   *   data: {
   *     // ... data to create a PriceEntry
   *   }
   * })
   * 
   */
  create<T extends PriceEntryCreateArgs>(args: Prisma.SelectSubset<T, PriceEntryCreateArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PriceEntries.
   * @param {PriceEntryCreateManyArgs} args - Arguments to create many PriceEntries.
   * @example
   * // Create many PriceEntries
   * const priceEntry = await prisma.priceEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PriceEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, PriceEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PriceEntries and returns the data saved in the database.
   * @param {PriceEntryCreateManyAndReturnArgs} args - Arguments to create many PriceEntries.
   * @example
   * // Create many PriceEntries
   * const priceEntry = await prisma.priceEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PriceEntries and only return the `id`
   * const priceEntryWithIdOnly = await prisma.priceEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PriceEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PriceEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PriceEntry.
   * @param {PriceEntryDeleteArgs} args - Arguments to delete one PriceEntry.
   * @example
   * // Delete one PriceEntry
   * const PriceEntry = await prisma.priceEntry.delete({
   *   where: {
   *     // ... filter to delete one PriceEntry
   *   }
   * })
   * 
   */
  delete<T extends PriceEntryDeleteArgs>(args: Prisma.SelectSubset<T, PriceEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PriceEntry.
   * @param {PriceEntryUpdateArgs} args - Arguments to update one PriceEntry.
   * @example
   * // Update one PriceEntry
   * const priceEntry = await prisma.priceEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PriceEntryUpdateArgs>(args: Prisma.SelectSubset<T, PriceEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PriceEntries.
   * @param {PriceEntryDeleteManyArgs} args - Arguments to filter PriceEntries to delete.
   * @example
   * // Delete a few PriceEntries
   * const { count } = await prisma.priceEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PriceEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, PriceEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PriceEntries
   * const priceEntry = await prisma.priceEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PriceEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, PriceEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PriceEntries and returns the data updated in the database.
   * @param {PriceEntryUpdateManyAndReturnArgs} args - Arguments to update many PriceEntries.
   * @example
   * // Update many PriceEntries
   * const priceEntry = await prisma.priceEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PriceEntries and only return the `id`
   * const priceEntryWithIdOnly = await prisma.priceEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PriceEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PriceEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PriceEntry.
   * @param {PriceEntryUpsertArgs} args - Arguments to update or create a PriceEntry.
   * @example
   * // Update or create a PriceEntry
   * const priceEntry = await prisma.priceEntry.upsert({
   *   create: {
   *     // ... data to create a PriceEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PriceEntry we want to update
   *   }
   * })
   */
  upsert<T extends PriceEntryUpsertArgs>(args: Prisma.SelectSubset<T, PriceEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__PriceEntryClient<runtime.Types.Result.GetResult<Prisma.$PriceEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PriceEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryCountArgs} args - Arguments to filter PriceEntries to count.
   * @example
   * // Count the number of PriceEntries
   * const count = await prisma.priceEntry.count({
   *   where: {
   *     // ... the filter for the PriceEntries we want to count
   *   }
   * })
  **/
  count<T extends PriceEntryCountArgs>(
    args?: Prisma.Subset<T, PriceEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PriceEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PriceEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PriceEntryAggregateArgs>(args: Prisma.Subset<T, PriceEntryAggregateArgs>): Prisma.PrismaPromise<GetPriceEntryAggregateType<T>>

  /**
   * Group by PriceEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PriceEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PriceEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PriceEntryGroupByArgs['orderBy'] }
      : { orderBy?: PriceEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PriceEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPriceEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PriceEntry model
 */
readonly fields: PriceEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PriceEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PriceEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  kit<T extends Prisma.KitDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KitDefaultArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PriceEntry model
 */
export interface PriceEntryFieldRefs {
  readonly id: Prisma.FieldRef<"PriceEntry", 'String'>
  readonly kitId: Prisma.FieldRef<"PriceEntry", 'String'>
  readonly storeId: Prisma.FieldRef<"PriceEntry", 'String'>
  readonly price: Prisma.FieldRef<"PriceEntry", 'Float'>
  readonly currency: Prisma.FieldRef<"PriceEntry", 'String'>
  readonly inStock: Prisma.FieldRef<"PriceEntry", 'Boolean'>
  readonly recordedAt: Prisma.FieldRef<"PriceEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PriceEntry findUnique
 */
export type PriceEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * Filter, which PriceEntry to fetch.
   */
  where: Prisma.PriceEntryWhereUniqueInput
}

/**
 * PriceEntry findUniqueOrThrow
 */
export type PriceEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * Filter, which PriceEntry to fetch.
   */
  where: Prisma.PriceEntryWhereUniqueInput
}

/**
 * PriceEntry findFirst
 */
export type PriceEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * Filter, which PriceEntry to fetch.
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceEntries to fetch.
   */
  orderBy?: Prisma.PriceEntryOrderByWithRelationInput | Prisma.PriceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceEntries.
   */
  cursor?: Prisma.PriceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceEntries.
   */
  distinct?: Prisma.PriceEntryScalarFieldEnum | Prisma.PriceEntryScalarFieldEnum[]
}

/**
 * PriceEntry findFirstOrThrow
 */
export type PriceEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * Filter, which PriceEntry to fetch.
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceEntries to fetch.
   */
  orderBy?: Prisma.PriceEntryOrderByWithRelationInput | Prisma.PriceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PriceEntries.
   */
  cursor?: Prisma.PriceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PriceEntries.
   */
  distinct?: Prisma.PriceEntryScalarFieldEnum | Prisma.PriceEntryScalarFieldEnum[]
}

/**
 * PriceEntry findMany
 */
export type PriceEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * Filter, which PriceEntries to fetch.
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PriceEntries to fetch.
   */
  orderBy?: Prisma.PriceEntryOrderByWithRelationInput | Prisma.PriceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PriceEntries.
   */
  cursor?: Prisma.PriceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PriceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PriceEntries.
   */
  skip?: number
  distinct?: Prisma.PriceEntryScalarFieldEnum | Prisma.PriceEntryScalarFieldEnum[]
}

/**
 * PriceEntry create
 */
export type PriceEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a PriceEntry.
   */
  data: Prisma.XOR<Prisma.PriceEntryCreateInput, Prisma.PriceEntryUncheckedCreateInput>
}

/**
 * PriceEntry createMany
 */
export type PriceEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PriceEntries.
   */
  data: Prisma.PriceEntryCreateManyInput | Prisma.PriceEntryCreateManyInput[]
}

/**
 * PriceEntry createManyAndReturn
 */
export type PriceEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * The data used to create many PriceEntries.
   */
  data: Prisma.PriceEntryCreateManyInput | Prisma.PriceEntryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PriceEntry update
 */
export type PriceEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a PriceEntry.
   */
  data: Prisma.XOR<Prisma.PriceEntryUpdateInput, Prisma.PriceEntryUncheckedUpdateInput>
  /**
   * Choose, which PriceEntry to update.
   */
  where: Prisma.PriceEntryWhereUniqueInput
}

/**
 * PriceEntry updateMany
 */
export type PriceEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PriceEntries.
   */
  data: Prisma.XOR<Prisma.PriceEntryUpdateManyMutationInput, Prisma.PriceEntryUncheckedUpdateManyInput>
  /**
   * Filter which PriceEntries to update
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * Limit how many PriceEntries to update.
   */
  limit?: number
}

/**
 * PriceEntry updateManyAndReturn
 */
export type PriceEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * The data used to update PriceEntries.
   */
  data: Prisma.XOR<Prisma.PriceEntryUpdateManyMutationInput, Prisma.PriceEntryUncheckedUpdateManyInput>
  /**
   * Filter which PriceEntries to update
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * Limit how many PriceEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PriceEntry upsert
 */
export type PriceEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the PriceEntry to update in case it exists.
   */
  where: Prisma.PriceEntryWhereUniqueInput
  /**
   * In case the PriceEntry found by the `where` argument doesn't exist, create a new PriceEntry with this data.
   */
  create: Prisma.XOR<Prisma.PriceEntryCreateInput, Prisma.PriceEntryUncheckedCreateInput>
  /**
   * In case the PriceEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PriceEntryUpdateInput, Prisma.PriceEntryUncheckedUpdateInput>
}

/**
 * PriceEntry delete
 */
export type PriceEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
  /**
   * Filter which PriceEntry to delete.
   */
  where: Prisma.PriceEntryWhereUniqueInput
}

/**
 * PriceEntry deleteMany
 */
export type PriceEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PriceEntries to delete
   */
  where?: Prisma.PriceEntryWhereInput
  /**
   * Limit how many PriceEntries to delete.
   */
  limit?: number
}

/**
 * PriceEntry without action
 */
export type PriceEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceEntry
   */
  select?: Prisma.PriceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceEntry
   */
  omit?: Prisma.PriceEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceEntryInclude<ExtArgs> | null
}
