
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StoreLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StoreLink
 * 
 */
export type StoreLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$StoreLinkPayload>

export type AggregateStoreLink = {
  _count: StoreLinkCountAggregateOutputType | null
  _min: StoreLinkMinAggregateOutputType | null
  _max: StoreLinkMaxAggregateOutputType | null
}

export type StoreLinkMinAggregateOutputType = {
  id: string | null
  kitId: string | null
  storeId: string | null
  url: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StoreLinkMaxAggregateOutputType = {
  id: string | null
  kitId: string | null
  storeId: string | null
  url: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StoreLinkCountAggregateOutputType = {
  id: number
  kitId: number
  storeId: number
  url: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StoreLinkMinAggregateInputType = {
  id?: true
  kitId?: true
  storeId?: true
  url?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type StoreLinkMaxAggregateInputType = {
  id?: true
  kitId?: true
  storeId?: true
  url?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type StoreLinkCountAggregateInputType = {
  id?: true
  kitId?: true
  storeId?: true
  url?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StoreLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoreLink to aggregate.
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreLinks to fetch.
   */
  orderBy?: Prisma.StoreLinkOrderByWithRelationInput | Prisma.StoreLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StoreLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StoreLinks
  **/
  _count?: true | StoreLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StoreLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StoreLinkMaxAggregateInputType
}

export type GetStoreLinkAggregateType<T extends StoreLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateStoreLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStoreLink[P]>
    : Prisma.GetScalarType<T[P], AggregateStoreLink[P]>
}




export type StoreLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoreLinkWhereInput
  orderBy?: Prisma.StoreLinkOrderByWithAggregationInput | Prisma.StoreLinkOrderByWithAggregationInput[]
  by: Prisma.StoreLinkScalarFieldEnum[] | Prisma.StoreLinkScalarFieldEnum
  having?: Prisma.StoreLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StoreLinkCountAggregateInputType | true
  _min?: StoreLinkMinAggregateInputType
  _max?: StoreLinkMaxAggregateInputType
}

export type StoreLinkGroupByOutputType = {
  id: string
  kitId: string
  storeId: string
  url: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: StoreLinkCountAggregateOutputType | null
  _min: StoreLinkMinAggregateOutputType | null
  _max: StoreLinkMaxAggregateOutputType | null
}

type GetStoreLinkGroupByPayload<T extends StoreLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StoreLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StoreLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StoreLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StoreLinkGroupByOutputType[P]>
      }
    >
  >



export type StoreLinkWhereInput = {
  AND?: Prisma.StoreLinkWhereInput | Prisma.StoreLinkWhereInput[]
  OR?: Prisma.StoreLinkWhereInput[]
  NOT?: Prisma.StoreLinkWhereInput | Prisma.StoreLinkWhereInput[]
  id?: Prisma.StringFilter<"StoreLink"> | string
  kitId?: Prisma.StringFilter<"StoreLink"> | string
  storeId?: Prisma.StringFilter<"StoreLink"> | string
  url?: Prisma.StringFilter<"StoreLink"> | string
  isActive?: Prisma.BoolFilter<"StoreLink"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StoreLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StoreLink"> | Date | string
  kit?: Prisma.XOR<Prisma.KitScalarRelationFilter, Prisma.KitWhereInput>
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
}

export type StoreLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  kit?: Prisma.KitOrderByWithRelationInput
  store?: Prisma.StoreOrderByWithRelationInput
}

export type StoreLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  kitId_storeId?: Prisma.StoreLinkKitIdStoreIdCompoundUniqueInput
  AND?: Prisma.StoreLinkWhereInput | Prisma.StoreLinkWhereInput[]
  OR?: Prisma.StoreLinkWhereInput[]
  NOT?: Prisma.StoreLinkWhereInput | Prisma.StoreLinkWhereInput[]
  kitId?: Prisma.StringFilter<"StoreLink"> | string
  storeId?: Prisma.StringFilter<"StoreLink"> | string
  url?: Prisma.StringFilter<"StoreLink"> | string
  isActive?: Prisma.BoolFilter<"StoreLink"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StoreLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StoreLink"> | Date | string
  kit?: Prisma.XOR<Prisma.KitScalarRelationFilter, Prisma.KitWhereInput>
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
}, "id" | "kitId_storeId">

export type StoreLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StoreLinkCountOrderByAggregateInput
  _max?: Prisma.StoreLinkMaxOrderByAggregateInput
  _min?: Prisma.StoreLinkMinOrderByAggregateInput
}

export type StoreLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.StoreLinkScalarWhereWithAggregatesInput | Prisma.StoreLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.StoreLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StoreLinkScalarWhereWithAggregatesInput | Prisma.StoreLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StoreLink"> | string
  kitId?: Prisma.StringWithAggregatesFilter<"StoreLink"> | string
  storeId?: Prisma.StringWithAggregatesFilter<"StoreLink"> | string
  url?: Prisma.StringWithAggregatesFilter<"StoreLink"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"StoreLink"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StoreLink"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StoreLink"> | Date | string
}

export type StoreLinkCreateInput = {
  id?: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  kit: Prisma.KitCreateNestedOneWithoutStoreLinksInput
  store: Prisma.StoreCreateNestedOneWithoutStoreLinksInput
}

export type StoreLinkUncheckedCreateInput = {
  id?: string
  kitId: string
  storeId: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kit?: Prisma.KitUpdateOneRequiredWithoutStoreLinksNestedInput
  store?: Prisma.StoreUpdateOneRequiredWithoutStoreLinksNestedInput
}

export type StoreLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreLinkCreateManyInput = {
  id?: string
  kitId: string
  storeId: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreLinkListRelationFilter = {
  every?: Prisma.StoreLinkWhereInput
  some?: Prisma.StoreLinkWhereInput
  none?: Prisma.StoreLinkWhereInput
}

export type StoreLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StoreLinkKitIdStoreIdCompoundUniqueInput = {
  kitId: string
  storeId: string
}

export type StoreLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreLinkCreateNestedManyWithoutKitInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutKitInput, Prisma.StoreLinkUncheckedCreateWithoutKitInput> | Prisma.StoreLinkCreateWithoutKitInput[] | Prisma.StoreLinkUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutKitInput | Prisma.StoreLinkCreateOrConnectWithoutKitInput[]
  createMany?: Prisma.StoreLinkCreateManyKitInputEnvelope
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
}

export type StoreLinkUncheckedCreateNestedManyWithoutKitInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutKitInput, Prisma.StoreLinkUncheckedCreateWithoutKitInput> | Prisma.StoreLinkCreateWithoutKitInput[] | Prisma.StoreLinkUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutKitInput | Prisma.StoreLinkCreateOrConnectWithoutKitInput[]
  createMany?: Prisma.StoreLinkCreateManyKitInputEnvelope
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
}

export type StoreLinkUpdateManyWithoutKitNestedInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutKitInput, Prisma.StoreLinkUncheckedCreateWithoutKitInput> | Prisma.StoreLinkCreateWithoutKitInput[] | Prisma.StoreLinkUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutKitInput | Prisma.StoreLinkCreateOrConnectWithoutKitInput[]
  upsert?: Prisma.StoreLinkUpsertWithWhereUniqueWithoutKitInput | Prisma.StoreLinkUpsertWithWhereUniqueWithoutKitInput[]
  createMany?: Prisma.StoreLinkCreateManyKitInputEnvelope
  set?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  disconnect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  delete?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  update?: Prisma.StoreLinkUpdateWithWhereUniqueWithoutKitInput | Prisma.StoreLinkUpdateWithWhereUniqueWithoutKitInput[]
  updateMany?: Prisma.StoreLinkUpdateManyWithWhereWithoutKitInput | Prisma.StoreLinkUpdateManyWithWhereWithoutKitInput[]
  deleteMany?: Prisma.StoreLinkScalarWhereInput | Prisma.StoreLinkScalarWhereInput[]
}

export type StoreLinkUncheckedUpdateManyWithoutKitNestedInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutKitInput, Prisma.StoreLinkUncheckedCreateWithoutKitInput> | Prisma.StoreLinkCreateWithoutKitInput[] | Prisma.StoreLinkUncheckedCreateWithoutKitInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutKitInput | Prisma.StoreLinkCreateOrConnectWithoutKitInput[]
  upsert?: Prisma.StoreLinkUpsertWithWhereUniqueWithoutKitInput | Prisma.StoreLinkUpsertWithWhereUniqueWithoutKitInput[]
  createMany?: Prisma.StoreLinkCreateManyKitInputEnvelope
  set?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  disconnect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  delete?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  update?: Prisma.StoreLinkUpdateWithWhereUniqueWithoutKitInput | Prisma.StoreLinkUpdateWithWhereUniqueWithoutKitInput[]
  updateMany?: Prisma.StoreLinkUpdateManyWithWhereWithoutKitInput | Prisma.StoreLinkUpdateManyWithWhereWithoutKitInput[]
  deleteMany?: Prisma.StoreLinkScalarWhereInput | Prisma.StoreLinkScalarWhereInput[]
}

export type StoreLinkCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutStoreInput, Prisma.StoreLinkUncheckedCreateWithoutStoreInput> | Prisma.StoreLinkCreateWithoutStoreInput[] | Prisma.StoreLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutStoreInput | Prisma.StoreLinkCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.StoreLinkCreateManyStoreInputEnvelope
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
}

export type StoreLinkUncheckedCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutStoreInput, Prisma.StoreLinkUncheckedCreateWithoutStoreInput> | Prisma.StoreLinkCreateWithoutStoreInput[] | Prisma.StoreLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutStoreInput | Prisma.StoreLinkCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.StoreLinkCreateManyStoreInputEnvelope
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
}

export type StoreLinkUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutStoreInput, Prisma.StoreLinkUncheckedCreateWithoutStoreInput> | Prisma.StoreLinkCreateWithoutStoreInput[] | Prisma.StoreLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutStoreInput | Prisma.StoreLinkCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.StoreLinkUpsertWithWhereUniqueWithoutStoreInput | Prisma.StoreLinkUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.StoreLinkCreateManyStoreInputEnvelope
  set?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  disconnect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  delete?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  update?: Prisma.StoreLinkUpdateWithWhereUniqueWithoutStoreInput | Prisma.StoreLinkUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.StoreLinkUpdateManyWithWhereWithoutStoreInput | Prisma.StoreLinkUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.StoreLinkScalarWhereInput | Prisma.StoreLinkScalarWhereInput[]
}

export type StoreLinkUncheckedUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.StoreLinkCreateWithoutStoreInput, Prisma.StoreLinkUncheckedCreateWithoutStoreInput> | Prisma.StoreLinkCreateWithoutStoreInput[] | Prisma.StoreLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.StoreLinkCreateOrConnectWithoutStoreInput | Prisma.StoreLinkCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.StoreLinkUpsertWithWhereUniqueWithoutStoreInput | Prisma.StoreLinkUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.StoreLinkCreateManyStoreInputEnvelope
  set?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  disconnect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  delete?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  connect?: Prisma.StoreLinkWhereUniqueInput | Prisma.StoreLinkWhereUniqueInput[]
  update?: Prisma.StoreLinkUpdateWithWhereUniqueWithoutStoreInput | Prisma.StoreLinkUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.StoreLinkUpdateManyWithWhereWithoutStoreInput | Prisma.StoreLinkUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.StoreLinkScalarWhereInput | Prisma.StoreLinkScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type StoreLinkCreateWithoutKitInput = {
  id?: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  store: Prisma.StoreCreateNestedOneWithoutStoreLinksInput
}

export type StoreLinkUncheckedCreateWithoutKitInput = {
  id?: string
  storeId: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreLinkCreateOrConnectWithoutKitInput = {
  where: Prisma.StoreLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreLinkCreateWithoutKitInput, Prisma.StoreLinkUncheckedCreateWithoutKitInput>
}

export type StoreLinkCreateManyKitInputEnvelope = {
  data: Prisma.StoreLinkCreateManyKitInput | Prisma.StoreLinkCreateManyKitInput[]
}

export type StoreLinkUpsertWithWhereUniqueWithoutKitInput = {
  where: Prisma.StoreLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.StoreLinkUpdateWithoutKitInput, Prisma.StoreLinkUncheckedUpdateWithoutKitInput>
  create: Prisma.XOR<Prisma.StoreLinkCreateWithoutKitInput, Prisma.StoreLinkUncheckedCreateWithoutKitInput>
}

export type StoreLinkUpdateWithWhereUniqueWithoutKitInput = {
  where: Prisma.StoreLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.StoreLinkUpdateWithoutKitInput, Prisma.StoreLinkUncheckedUpdateWithoutKitInput>
}

export type StoreLinkUpdateManyWithWhereWithoutKitInput = {
  where: Prisma.StoreLinkScalarWhereInput
  data: Prisma.XOR<Prisma.StoreLinkUpdateManyMutationInput, Prisma.StoreLinkUncheckedUpdateManyWithoutKitInput>
}

export type StoreLinkScalarWhereInput = {
  AND?: Prisma.StoreLinkScalarWhereInput | Prisma.StoreLinkScalarWhereInput[]
  OR?: Prisma.StoreLinkScalarWhereInput[]
  NOT?: Prisma.StoreLinkScalarWhereInput | Prisma.StoreLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"StoreLink"> | string
  kitId?: Prisma.StringFilter<"StoreLink"> | string
  storeId?: Prisma.StringFilter<"StoreLink"> | string
  url?: Prisma.StringFilter<"StoreLink"> | string
  isActive?: Prisma.BoolFilter<"StoreLink"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StoreLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StoreLink"> | Date | string
}

export type StoreLinkCreateWithoutStoreInput = {
  id?: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  kit: Prisma.KitCreateNestedOneWithoutStoreLinksInput
}

export type StoreLinkUncheckedCreateWithoutStoreInput = {
  id?: string
  kitId: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreLinkCreateOrConnectWithoutStoreInput = {
  where: Prisma.StoreLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreLinkCreateWithoutStoreInput, Prisma.StoreLinkUncheckedCreateWithoutStoreInput>
}

export type StoreLinkCreateManyStoreInputEnvelope = {
  data: Prisma.StoreLinkCreateManyStoreInput | Prisma.StoreLinkCreateManyStoreInput[]
}

export type StoreLinkUpsertWithWhereUniqueWithoutStoreInput = {
  where: Prisma.StoreLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.StoreLinkUpdateWithoutStoreInput, Prisma.StoreLinkUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.StoreLinkCreateWithoutStoreInput, Prisma.StoreLinkUncheckedCreateWithoutStoreInput>
}

export type StoreLinkUpdateWithWhereUniqueWithoutStoreInput = {
  where: Prisma.StoreLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.StoreLinkUpdateWithoutStoreInput, Prisma.StoreLinkUncheckedUpdateWithoutStoreInput>
}

export type StoreLinkUpdateManyWithWhereWithoutStoreInput = {
  where: Prisma.StoreLinkScalarWhereInput
  data: Prisma.XOR<Prisma.StoreLinkUpdateManyMutationInput, Prisma.StoreLinkUncheckedUpdateManyWithoutStoreInput>
}

export type StoreLinkCreateManyKitInput = {
  id?: string
  storeId: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreLinkUpdateWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.StoreUpdateOneRequiredWithoutStoreLinksNestedInput
}

export type StoreLinkUncheckedUpdateWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreLinkUncheckedUpdateManyWithoutKitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreLinkCreateManyStoreInput = {
  id?: string
  kitId: string
  url: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreLinkUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kit?: Prisma.KitUpdateOneRequiredWithoutStoreLinksNestedInput
}

export type StoreLinkUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreLinkUncheckedUpdateManyWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kitId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StoreLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  url?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeLink"]>

export type StoreLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  url?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeLink"]>

export type StoreLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  url?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeLink"]>

export type StoreLinkSelectScalar = {
  id?: boolean
  kitId?: boolean
  storeId?: boolean
  url?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StoreLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "kitId" | "storeId" | "url" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["storeLink"]>
export type StoreLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}
export type StoreLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}
export type StoreLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kit?: boolean | Prisma.KitDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}

export type $StoreLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StoreLink"
  objects: {
    kit: Prisma.$KitPayload<ExtArgs>
    store: Prisma.$StorePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    kitId: string
    storeId: string
    url: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["storeLink"]>
  composites: {}
}

export type StoreLinkGetPayload<S extends boolean | null | undefined | StoreLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload, S>

export type StoreLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StoreLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StoreLinkCountAggregateInputType | true
  }

export interface StoreLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StoreLink'], meta: { name: 'StoreLink' } }
  /**
   * Find zero or one StoreLink that matches the filter.
   * @param {StoreLinkFindUniqueArgs} args - Arguments to find a StoreLink
   * @example
   * // Get one StoreLink
   * const storeLink = await prisma.storeLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StoreLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, StoreLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StoreLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StoreLinkFindUniqueOrThrowArgs} args - Arguments to find a StoreLink
   * @example
   * // Get one StoreLink
   * const storeLink = await prisma.storeLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StoreLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StoreLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoreLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkFindFirstArgs} args - Arguments to find a StoreLink
   * @example
   * // Get one StoreLink
   * const storeLink = await prisma.storeLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StoreLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, StoreLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoreLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkFindFirstOrThrowArgs} args - Arguments to find a StoreLink
   * @example
   * // Get one StoreLink
   * const storeLink = await prisma.storeLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StoreLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StoreLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StoreLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StoreLinks
   * const storeLinks = await prisma.storeLink.findMany()
   * 
   * // Get first 10 StoreLinks
   * const storeLinks = await prisma.storeLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const storeLinkWithIdOnly = await prisma.storeLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StoreLinkFindManyArgs>(args?: Prisma.SelectSubset<T, StoreLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StoreLink.
   * @param {StoreLinkCreateArgs} args - Arguments to create a StoreLink.
   * @example
   * // Create one StoreLink
   * const StoreLink = await prisma.storeLink.create({
   *   data: {
   *     // ... data to create a StoreLink
   *   }
   * })
   * 
   */
  create<T extends StoreLinkCreateArgs>(args: Prisma.SelectSubset<T, StoreLinkCreateArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StoreLinks.
   * @param {StoreLinkCreateManyArgs} args - Arguments to create many StoreLinks.
   * @example
   * // Create many StoreLinks
   * const storeLink = await prisma.storeLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StoreLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, StoreLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StoreLinks and returns the data saved in the database.
   * @param {StoreLinkCreateManyAndReturnArgs} args - Arguments to create many StoreLinks.
   * @example
   * // Create many StoreLinks
   * const storeLink = await prisma.storeLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StoreLinks and only return the `id`
   * const storeLinkWithIdOnly = await prisma.storeLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StoreLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StoreLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StoreLink.
   * @param {StoreLinkDeleteArgs} args - Arguments to delete one StoreLink.
   * @example
   * // Delete one StoreLink
   * const StoreLink = await prisma.storeLink.delete({
   *   where: {
   *     // ... filter to delete one StoreLink
   *   }
   * })
   * 
   */
  delete<T extends StoreLinkDeleteArgs>(args: Prisma.SelectSubset<T, StoreLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StoreLink.
   * @param {StoreLinkUpdateArgs} args - Arguments to update one StoreLink.
   * @example
   * // Update one StoreLink
   * const storeLink = await prisma.storeLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StoreLinkUpdateArgs>(args: Prisma.SelectSubset<T, StoreLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StoreLinks.
   * @param {StoreLinkDeleteManyArgs} args - Arguments to filter StoreLinks to delete.
   * @example
   * // Delete a few StoreLinks
   * const { count } = await prisma.storeLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StoreLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, StoreLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoreLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StoreLinks
   * const storeLink = await prisma.storeLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StoreLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, StoreLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoreLinks and returns the data updated in the database.
   * @param {StoreLinkUpdateManyAndReturnArgs} args - Arguments to update many StoreLinks.
   * @example
   * // Update many StoreLinks
   * const storeLink = await prisma.storeLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StoreLinks and only return the `id`
   * const storeLinkWithIdOnly = await prisma.storeLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StoreLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StoreLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StoreLink.
   * @param {StoreLinkUpsertArgs} args - Arguments to update or create a StoreLink.
   * @example
   * // Update or create a StoreLink
   * const storeLink = await prisma.storeLink.upsert({
   *   create: {
   *     // ... data to create a StoreLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StoreLink we want to update
   *   }
   * })
   */
  upsert<T extends StoreLinkUpsertArgs>(args: Prisma.SelectSubset<T, StoreLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__StoreLinkClient<runtime.Types.Result.GetResult<Prisma.$StoreLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StoreLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkCountArgs} args - Arguments to filter StoreLinks to count.
   * @example
   * // Count the number of StoreLinks
   * const count = await prisma.storeLink.count({
   *   where: {
   *     // ... the filter for the StoreLinks we want to count
   *   }
   * })
  **/
  count<T extends StoreLinkCountArgs>(
    args?: Prisma.Subset<T, StoreLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StoreLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StoreLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StoreLinkAggregateArgs>(args: Prisma.Subset<T, StoreLinkAggregateArgs>): Prisma.PrismaPromise<GetStoreLinkAggregateType<T>>

  /**
   * Group by StoreLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StoreLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StoreLinkGroupByArgs['orderBy'] }
      : { orderBy?: StoreLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StoreLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStoreLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StoreLink model
 */
readonly fields: StoreLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StoreLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StoreLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  kit<T extends Prisma.KitDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KitDefaultArgs<ExtArgs>>): Prisma.Prisma__KitClient<runtime.Types.Result.GetResult<Prisma.$KitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  store<T extends Prisma.StoreDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StoreDefaultArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StoreLink model
 */
export interface StoreLinkFieldRefs {
  readonly id: Prisma.FieldRef<"StoreLink", 'String'>
  readonly kitId: Prisma.FieldRef<"StoreLink", 'String'>
  readonly storeId: Prisma.FieldRef<"StoreLink", 'String'>
  readonly url: Prisma.FieldRef<"StoreLink", 'String'>
  readonly isActive: Prisma.FieldRef<"StoreLink", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"StoreLink", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StoreLink", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StoreLink findUnique
 */
export type StoreLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * Filter, which StoreLink to fetch.
   */
  where: Prisma.StoreLinkWhereUniqueInput
}

/**
 * StoreLink findUniqueOrThrow
 */
export type StoreLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * Filter, which StoreLink to fetch.
   */
  where: Prisma.StoreLinkWhereUniqueInput
}

/**
 * StoreLink findFirst
 */
export type StoreLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * Filter, which StoreLink to fetch.
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreLinks to fetch.
   */
  orderBy?: Prisma.StoreLinkOrderByWithRelationInput | Prisma.StoreLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoreLinks.
   */
  cursor?: Prisma.StoreLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreLinks.
   */
  distinct?: Prisma.StoreLinkScalarFieldEnum | Prisma.StoreLinkScalarFieldEnum[]
}

/**
 * StoreLink findFirstOrThrow
 */
export type StoreLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * Filter, which StoreLink to fetch.
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreLinks to fetch.
   */
  orderBy?: Prisma.StoreLinkOrderByWithRelationInput | Prisma.StoreLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoreLinks.
   */
  cursor?: Prisma.StoreLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreLinks.
   */
  distinct?: Prisma.StoreLinkScalarFieldEnum | Prisma.StoreLinkScalarFieldEnum[]
}

/**
 * StoreLink findMany
 */
export type StoreLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * Filter, which StoreLinks to fetch.
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreLinks to fetch.
   */
  orderBy?: Prisma.StoreLinkOrderByWithRelationInput | Prisma.StoreLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StoreLinks.
   */
  cursor?: Prisma.StoreLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreLinks.
   */
  skip?: number
  distinct?: Prisma.StoreLinkScalarFieldEnum | Prisma.StoreLinkScalarFieldEnum[]
}

/**
 * StoreLink create
 */
export type StoreLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a StoreLink.
   */
  data: Prisma.XOR<Prisma.StoreLinkCreateInput, Prisma.StoreLinkUncheckedCreateInput>
}

/**
 * StoreLink createMany
 */
export type StoreLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StoreLinks.
   */
  data: Prisma.StoreLinkCreateManyInput | Prisma.StoreLinkCreateManyInput[]
}

/**
 * StoreLink createManyAndReturn
 */
export type StoreLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * The data used to create many StoreLinks.
   */
  data: Prisma.StoreLinkCreateManyInput | Prisma.StoreLinkCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StoreLink update
 */
export type StoreLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a StoreLink.
   */
  data: Prisma.XOR<Prisma.StoreLinkUpdateInput, Prisma.StoreLinkUncheckedUpdateInput>
  /**
   * Choose, which StoreLink to update.
   */
  where: Prisma.StoreLinkWhereUniqueInput
}

/**
 * StoreLink updateMany
 */
export type StoreLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StoreLinks.
   */
  data: Prisma.XOR<Prisma.StoreLinkUpdateManyMutationInput, Prisma.StoreLinkUncheckedUpdateManyInput>
  /**
   * Filter which StoreLinks to update
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * Limit how many StoreLinks to update.
   */
  limit?: number
}

/**
 * StoreLink updateManyAndReturn
 */
export type StoreLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * The data used to update StoreLinks.
   */
  data: Prisma.XOR<Prisma.StoreLinkUpdateManyMutationInput, Prisma.StoreLinkUncheckedUpdateManyInput>
  /**
   * Filter which StoreLinks to update
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * Limit how many StoreLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StoreLink upsert
 */
export type StoreLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the StoreLink to update in case it exists.
   */
  where: Prisma.StoreLinkWhereUniqueInput
  /**
   * In case the StoreLink found by the `where` argument doesn't exist, create a new StoreLink with this data.
   */
  create: Prisma.XOR<Prisma.StoreLinkCreateInput, Prisma.StoreLinkUncheckedCreateInput>
  /**
   * In case the StoreLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StoreLinkUpdateInput, Prisma.StoreLinkUncheckedUpdateInput>
}

/**
 * StoreLink delete
 */
export type StoreLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
  /**
   * Filter which StoreLink to delete.
   */
  where: Prisma.StoreLinkWhereUniqueInput
}

/**
 * StoreLink deleteMany
 */
export type StoreLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoreLinks to delete
   */
  where?: Prisma.StoreLinkWhereInput
  /**
   * Limit how many StoreLinks to delete.
   */
  limit?: number
}

/**
 * StoreLink without action
 */
export type StoreLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreLink
   */
  select?: Prisma.StoreLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreLink
   */
  omit?: Prisma.StoreLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreLinkInclude<ExtArgs> | null
}
